#!/usr/bin/env node
/**
 * addLeadActors.mjs
 * Enriches puzzle_pool.json with lead actor data for shows missing it.
 * Run: node scripts/addLeadActors.mjs
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, '../data/puzzle_pool.json');

// Map of show slug ID → lead actor name
const LEAD_ACTOR_MAP = {
  // Drama / Thriller
  'the-big-bang-theory':                   'Jim Parsons',
  'how-i-met-your-mother':                 'Josh Radnor',
  'prison-break':                          'Wentworth Miller',
  'the-queen-s-gambit':                    'Anya Taylor-Joy',
  'vikings':                               'Travis Fimmel',
  'the-witcher':                           'Henry Cavill',
  'modern-family':                         'Ed O\'Neill',
  'suits':                                 'Gabriel Macht',
  'supernatural':                          'Jensen Ackles',
  'narcos':                                'Wagner Moura',
  'wednesday':                             'Jenna Ortega',
  'brooklyn-nine-nine':                    'Andy Samberg',
  'wandavision':                           'Elizabeth Olsen',
  'sex-education':                         'Asa Butterfield',
  'mindhunter':                            'Jonathan Groff',
  'seinfeld':                              'Jerry Seinfeld',
  'fallout':                               'Ella Purnell',
  'the-vampire-diaries':                   'Nina Dobrev',
  'you':                                   'Penn Badgley',
  'sons-of-anarchy':                       'Charlie Hunnam',
  '13-reasons-why':                        'Katherine Langford',
  'orange-is-the-new-black':               'Taylor Schilling',
  'the-haunting-of-hill-house':            'Michiel Huisman',
  'the-umbrella-academy':                  'Elliot Page',
  'parks-and-recreation':                  'Amy Poehler',
  'community':                             'Joel McHale',
  'moon-knight':                           'Oscar Isaac',
  'hannibal':                              'Mads Mikkelsen',
  'the-100':                               'Eliza Taylor',
  'firefly':                               'Nathan Fillion',
  'the-handmaid-s-tale':                   'Elisabeth Moss',
  'spartacus':                             'Andy Whitfield',
  'reacher':                               'Alan Ritchson',
  'scrubs':                                'Zach Braff',
  'the-falcon-and-the-winter-soldier':     'Anthony Mackie',
  'fringe':                                'Anna Torv',
  'new-girl':                              'Zooey Deschanel',
  'obi-wan-kenobi':                        'Ewan McGregor',
  'gotham':                                'Ben McKenzie',
  'once-upon-a-time':                      'Jennifer Morrison',
  'hawkeye':                               'Jeremy Renner',
  'cobra-kai':                             'William Zabka',
  'sh-gun':                                'Hiroyuki Sanada',
  'criminal-minds':                        'Matthew Gray Gubler',
  'agents-of-s-h-i-e-l-d':               'Clark Gregg',
  'the-penguin':                           'Colin Farrell',
  'the-mentalist':                         'Simon Baker',
  'mare-of-easttown':                      'Kate Winslet',
  'the-good-place':                        'Kristen Bell',
  'the-sandman':                           'Tom Sturridge',
  'she-hulk-attorney-at-law':              'Tatiana Maslany',
  'the-book-of-boba-fett':                 'Temuera Morrison',
  'rome':                                  'Kevin McKidd',
  'altered-carbon':                        'Joel Kinnaman',
  'that-70s-show':                         'Topher Grace',
  'outlander':                             'Caitríona Balfe',
  'californication':                       'David Duchovny',
  'tom-clancy-s-jack-ryan':               'John Krasinski',
  'the-expanse':                           'Steven Strait',
  'peacemaker':                            'John Cena',
  'bones':                                 'Emily Deschanel',
  'the-end-of-the-f-ing-world':            'Alex Lawther',
  'the-vampire-diaries':                   'Nina Dobrev',
  'the-100':                               'Eliza Taylor',
  'schitt-s-creek':                        'Eugene Levy',
  'sense8':                                'Doona Bae',
  'bodyguard':                             'Richard Madden',
  'six-feet-under':                        'Peter Krause',
  'curb-your-enthusiasm':                  'Larry David',
  'riverdale':                             'KJ Apa',
  'freaks-and-geeks':                      'Linda Cardellini',
  'the-wheel-of-time':                     'Rosamund Pike',
  'taboo':                                 'Tom Hardy',
  'glee':                                  'Lea Michele',
  '1883':                                  'Tim McGraw',
  'sex-and-the-city':                      'Sarah Jessica Parker',
  'lupin':                                 'Omar Sy',
  'chuck':                                 'Zachary Levi',
  'fear-the-walking-dead':                 'Kim Dickens',
  'desperate-housewives':                  'Teri Hatcher',
  'the-fresh-prince-of-bel-air':           'Will Smith',
  'the-night-agent':                       'Gabriel Basso',
  'the-sinner':                            'Jessica Biel',
  'smallville':                            'Tom Welling',
  'dexter-new-blood':                      'Michael C. Hall',
  'the-legend-of-korra':                   'Janet Varney',
  'the-morning-show':                      'Jennifer Aniston',
  'iron-fist':                             'Finn Jones',
  'luke-cage':                             'Mike Colter',
  'gen-v':                                 'Jaz Sinclair',
  'banshee':                               'Antony Starr',
  'young-sheldon':                         'Iain Armitage',
  'alice-in-borderland':                   'Kento Yamazaki',
  'emily-in-paris':                        'Lily Collins',
  'broadchurch':                           'Olivia Colman',
  'grimm':                                 'David Giuntoli',
  'ahsoka':                                'Rosario Dawson',
  'penny-dreadful':                        'Eva Green',
  'lie-to-me':                             'Tim Roth',
  'supergirl':                             'Melissa Benoist',
  'the-fall-of-the-house-of-usher':        'Bruce Greenwood',
  'the-killing':                           'Mireille Enos',
  'the-night-manager':                     'Tom Hiddleston',
  'the-good-doctor':                       'Freddie Highmore',
  'deadwood':                              'Timothy Olyphant',
  'the-oa':                                'Brit Marling',
  'the-terminal-list':                     'Chris Pratt',
  'elementary':                            'Jonny Lee Miller',
  'black-sails':                           'Toby Stephens',
  'shadow-and-bone':                       'Jessie Mei Li',
  'good-omens':                            'David Tennant',
  'weeds':                                 'Mary-Louise Parker',
  '1899':                                  'Emily Beecham',
  'the-defenders':                         'Charlie Cox',
  'outer-banks':                           'Chase Stokes',
  'yellowjackets':                         'Melanie Lynskey',
  'nine-perfect-strangers':               'Nicole Kidman',
  'penny-dreadful-city-of-angels':         'Natalie Dormer',
  'the-last-dance':                        'Michael Jordan',
  'the-haunting-of-bly-manor':             'Victoria Pedretti',
  'midnight-mass':                         'Hamish Linklater',
  'the-fall':                              'Gillian Anderson',
  'station-eleven':                        'Mackenzie Davis',
  'ozark':                                 'Jason Bateman',
  'succession':                            'Jeremy Strong',
  'fleabag':                               'Phoebe Waller-Bridge',
  'severance':                             'Adam Scott',
  'the-white-lotus':                       'Murray Bartlett',
  'euphoria':                              'Zendaya',
  'for-all-mankind':                       'Joel Kinnaman',
  'slow-horses':                           'Gary Oldman',
  'bad-sisters':                           'Sharon Horgan',
  'beef':                                  'Steven Yeun',
  'the-bear':                              'Jeremy Allen White',
  'abbott-elementary':                     'Quinta Brunson',
  'what-we-do-in-the-shadows':             'Kayvan Novak',
  'only-murders-in-the-building':          'Steve Martin',
  'the-marvelous-mrs-maisel':              'Rachel Brosnahan',
  'hacks':                                 'Jean Smart',
  'ted-lasso':                             'Jason Sudeikis',
  'the-last-of-us':                        'Pedro Pascal',
  'andor':                                 'Diego Luna',
  'the-crown':                             'Claire Foy',
  'house-of-the-dragon':                   'Matt Smith',
  'the-rings-of-power':                    'Morfydd Clark',
  'the-lord-of-the-rings-the-rings-of-power': 'Morfydd Clark',
  'silo':                                  'Rebecca Ferguson',
  'the-diplomat':                          'Keri Russell',
  'the-old-man':                           'Jeff Bridges',
  'say-nothing':                           'Maxine Peake',
  'the-penguin':                           'Colin Farrell',
  'shogun':                                'Hiroyuki Sanada',
  'barry':                                 'Bill Hader',
  'atlanta':                               'Donald Glover',
  'silicon-valley':                        'Thomas Middleditch',
  'veep':                                  'Julia Louis-Dreyfus',
  'the-boys':                              'Karl Urban',
  'invincible':                            'Steven Yeun',
  'arcane':                                'Hailee Steinfeld',
  'yellowstone':                           'Kevin Costner',
  'house-of-cards':                        'Kevin Spacey',
  'the-good-fight':                        'Christine Baranski',
  'killing-eve':                           'Sandra Oh',
  'the-night-of':                          'Riz Ahmed',
  'black-bird':                            'Taron Egerton',
  'the-umbrella-academy':                  'Elliot Page',
  'the-witcher':                           'Henry Cavill',
  'bridgerton':                            'Phoebe Dynevor',
  'the-flash':                             'Grant Gustin',
  'arrow':                                 'Stephen Amell',
  'grey-s-anatomy':                        'Ellen Pompeo',
  'castle':                                'Nathan Fillion',
  'law-order-special-victims-unit':        'Mariska Hargitay',
  'law-order-svu':                         'Mariska Hargitay',
  'empire':                                'Taraji P. Henson',
  'how-to-get-away-with-murder':           'Viola Davis',
  'ncis':                                  'Mark Harmon',
  'csi-crime-scene-investigation':         'William Petersen',
  'criminal-minds':                        'Matthew Gray Gubler',
  'white-collar':                          'Matt Bomer',
  'burn-notice':                           'Jeffrey Donovan',
  'leverage':                              'Timothy Hutton',
  'monk':                                  'Tony Shalhoub',
  'the-blacklist':                         'James Spader',
  'homeland':                              'Claire Danes',
  'true-blood':                            'Anna Paquin',
  'american-horror-story':                 'Evan Peters',
  'american-crime-story':                  'Sterling K. Brown',
  'big-little-lies':                       'Nicole Kidman',
  'downton-abbey':                         'Hugh Bonneville',
  'the-leftovers':                         'Justin Theroux',
  'happy-valley':                          'Sarah Lancashire',
  'bates-motel':                           'Vera Farmiga',
  'the-good-wife':                         'Julianna Margulies',
  'orphan-black':                          'Tatiana Maslany',
  'dark':                                  'Louis Hofmann',
  'damages':                               'Glenn Close',
  'bloodline':                             'Kyle Chandler',
  'the-newsroom':                          'Jeff Daniels',
  'city-on-a-hill':                        'Kevin Bacon',
  'justified':                             'Timothy Olyphant',
  'daredevil':                             'Charlie Cox',
  'jessica-jones':                         'Krysten Ritter',
  'the-punisher':                          'Jon Bernthal',
  'the-outsider':                          'Ben Mendelsohn',
  'mare-of-easttown':                      'Kate Winslet',
  'perry-mason':                           'Matthew Rhys',
  'the-night-manager':                     'Tom Hiddleston',
  'the-terror':                            'Jared Harris',
  'under-the-banner-of-heaven':            'Andrew Garfield',
  'show-me-a-hero':                        'Oscar Isaac',
  'halston':                               'Ewan McGregor',
  'the-plot-against-america':              'Winona Ryder',
  'the-comeback':                          'Lisa Kudrow',
  'new-amsterdam':                         'Ryan Eggold',
  'revenge':                               'Emily VanCamp',
  'saving-grace':                          'Holly Hunter',
  'the-pacific':                           'James Badge Dale',
  'in-treatment':                          'Gabriel Byrne',
  'nurse-Jackie':                          'Edie Falco',
  'nurse-jackie':                          'Edie Falco',
  'madam-secretary':                       'Téa Leoni',
  'humans':                                'Gemma Chan',
  'spin-city':                             'Michael J. Fox',
  'the-following':                         'Kevin Bacon',
  'skins':                                 'Nicholas Hoult',
  'the-it-crowd':                          'Chris O\'Dowd',
  'extras':                                'Ricky Gervais',
  '30-rock':                               'Tina Fey',
  'its-always-sunny-in-philadelphia':      'Charlie Day',
  'it-s-always-sunny-in-philadelphia':     'Charlie Day',
  'arrested-development':                  'Jason Bateman',
  'bojack-horseman':                       'Will Arnett',
  'rick-and-morty':                        'Justin Roiland',
  'the-simpsons':                          'Dan Castellaneta',
  'south-park':                            'Trey Parker',
  'family-guy':                            'Seth MacFarlane',
  'futurama':                              'Billy West',
  'archer':                                'H. Jon Benjamin',
  'gravity-falls':                         'Jason Ritter',
  'avatar-the-last-airbender':             'Zach Tyler Eisen',
  'the-legend-of-korra':                   'Janet Varney',
  'adventure-time':                        'Jeremy Shada',
  'batman-the-animated-series':            'Kevin Conroy',
  'spongebob-squarepants':                 'Tom Kenny',
  'star-trek-the-next-generation':         'Patrick Stewart',
  'star-trek-discovery':                   'Sonequa Martin-Green',
  'star-wars-the-clone-wars':              'Matt Lanter',
  'the-mandalorian':                       'Pedro Pascal',
  'andor':                                 'Diego Luna',
  'obi-wan-kenobi':                        'Ewan McGregor',
  'ahsoka':                                'Rosario Dawson',
  'the-book-of-boba-fett':                 'Temuera Morrison',
  'loki':                                  'Tom Hiddleston',
  'wandavision':                           'Elizabeth Olsen',
  'the-falcon-and-the-winter-soldier':     'Anthony Mackie',
  'hawkeye':                               'Jeremy Renner',
  'moon-knight':                           'Oscar Isaac',
  'ms-marvel':                             'Iman Vellani',
  'she-hulk-attorney-at-law':              'Tatiana Maslany',
  'peacemaker':                            'John Cena',
  'gen-v':                                 'Jaz Sinclair',
  'daredevil':                             'Charlie Cox',
  'jessica-jones':                         'Krysten Ritter',
  'luke-cage':                             'Mike Colter',
  'iron-fist':                             'Finn Jones',
  'the-defenders':                         'Charlie Cox',
  'the-punisher':                          'Jon Bernthal',
  'attack-on-titan':                       'Yuki Kaji',
  'demon-slayer-kimetsu-no-yaiba':         'Natsuki Hanae',
  'naruto-shippuden':                      'Junko Takeuchi',
  'naruto':                                'Junko Takeuchi',
  'one-piece':                             'Mayumi Tanaka',
  'death-note':                            'Mamoru Miyano',
  'fullmetal-alchemist-brotherhood':       'Romi Park',
  'jujutsu-kaisen':                        'Junya Enoki',
  'hunter-x-hunter':                       'Megumi Han',
  'one-punch-man':                         'Makoto Furukawa',
  'dragon-ball-z':                         'Masako Nozawa',
  'vinland-saga':                          'Yuto Uemura',
  'monster':                               'Hideaki Tezuka',
  'cowboy-bebop':                          'Koichi Yamadera',
  'cyberpunk-edgerunners':                 'Zach Aguilar',
  'planet-earth':                          'David Attenborough',
  'planet-earth-ii':                       'David Attenborough',
  'cosmos-a-spacetime-odyssey':            'Neil deGrasse Tyson',
  'top-gear':                              'Jeremy Clarkson',
  'the-last-dance':                        'Michael Jordan',
  'scam-1992-the-harshad-mehta-story':     'Pratik Gandhi',
  'money-heist':                           'Álvaro Morte',
  'squid-game':                            'Lee Jung-jae',
  'dark':                                  'Louis Hofmann',
  'alice-in-borderland':                   'Kento Yamazaki',
  'sense8':                                'Doona Bae',
  'lupin':                                 'Omar Sy',
  'emily-in-paris':                        'Lily Collins',
  '1899':                                  'Emily Beecham',
  'from':                                  'Harold Perrineau',
  'the-sinner':                            'Jessica Biel',
  'the-night-agent':                       'Gabriel Basso',
  'broadchurch':                           'Olivia Colman',
  'bodyguard':                             'Richard Madden',
  'after-life':                            'Ricky Gervais',
  'the-morning-show':                      'Jennifer Aniston',
  'nine-perfect-strangers':               'Nicole Kidman',
  'the-haunting-of-bly-manor':             'Victoria Pedretti',
  'the-fall-of-the-house-of-usher':        'Bruce Greenwood',
  'the-oa':                                'Brit Marling',
  'mr-bean':                               'Rowan Atkinson',
  'freaks-and-geeks':                      'Linda Cardellini',
  'gossip-girl':                           'Blake Lively',
  'pretty-little-liars':                   'Lucy Hale',
  'riverdale':                             'KJ Apa',
  'teen-wolf':                             'Tyler Posey',
  'the-vampire-diaries':                   'Nina Dobrev',
  'the-originals':                         'Joseph Morgan',
  'the-100':                               'Eliza Taylor',
  'smallville':                            'Tom Welling',
  'glee':                                  'Lea Michele',
  'desperate-housewives':                  'Teri Hatcher',
  'sex-and-the-city':                      'Sarah Jessica Parker',
  'the-fresh-prince-of-bel-air':           'Will Smith',
  'gilmore-girls':                         'Lauren Graham',
  'this-is-us':                            'Milo Ventimiglia',
  'modern-family':                         'Ed O\'Neill',
  'the-good-place':                        'Kristen Bell',
  'community':                             'Joel McHale',
  'parks-and-recreation':                  'Amy Poehler',
  'scrubs':                                'Zach Braff',
  'new-girl':                              'Zooey Deschanel',
  'malcolm-in-the-middle':                 'Frankie Muniz',
  'two-and-a-half-men':                    'Charlie Sheen',
  'young-sheldon':                         'Iain Armitage',
  'schitt-s-creek':                        'Eugene Levy',
  '30-rock':                               'Tina Fey',
  'the-good-fight':                        'Christine Baranski',
  'weeds':                                 'Mary-Louise Parker',
  'the-comeback':                          'Lisa Kudrow',
  'californication':                       'David Duchovny',
  'entourage':                             'Adrian Grenier',
  'silicon-valley':                        'Thomas Middleditch',
  'veep':                                  'Julia Louis-Dreyfus',
  'curb-your-enthusiasm':                  'Larry David',
  'succession':                            'Jeremy Strong',
  'fleabag':                               'Phoebe Waller-Bridge',
  'what-we-do-in-the-shadows':             'Kayvan Novak',
  'only-murders-in-the-building':          'Steve Martin',
  'hacks':                                 'Jean Smart',
  'abbott-elementary':                     'Quinta Brunson',
  'ted-lasso':                             'Jason Sudeikis',
  'the-bear':                              'Jeremy Allen White',
  'barry':                                 'Bill Hader',
  'atlanta':                               'Donald Glover',
  'the-marvelous-mrs-maisel':              'Rachel Brosnahan',
  'the-mandalorian':                       'Pedro Pascal',
  'arcane':                                'Hailee Steinfeld',
  'invincible':                            'Steven Yeun',
  'the-boys':                              'Karl Urban',
  'the-last-of-us':                        'Pedro Pascal',
  'the-witcher':                           'Henry Cavill',
  'yellowstone':                           'Kevin Costner',
  'bridgerton':                            'Phoebe Dynevor',
  'squid-game':                            'Lee Jung-jae',
  'ozark':                                 'Jason Bateman',
  'stranger-things':                       'Millie Bobby Brown',
  'game-of-thrones':                       'Peter Dinklage',
  'breaking-bad':                          'Bryan Cranston',
  'the-sopranos':                          'James Gandolfini',
  'the-wire':                              'Dominic West',
  'better-call-saul':                      'Bob Odenkirk',
  'chernobyl':                             'Jared Harris',
  'band-of-brothers':                      'Damian Lewis',
  'true-detective':                        'Matthew McConaughey',
  'fargo':                                 'Billy Bob Thornton',
  'sherlock':                              'Benedict Cumberbatch',
  'black-mirror':                          'Daniel Kaluuya',
  'severance':                             'Adam Scott',
  'the-white-lotus':                       'Murray Bartlett',
  'euphoria':                              'Zendaya',
  'mindhunter':                            'Jonathan Groff',
  'narcos':                                'Wagner Moura',
  'boardwalk-empire':                      'Steve Buscemi',
  'billions':                              'Damian Lewis',
  'doctor-who':                            'David Tennant',
  'the-crown':                             'Claire Foy',
  'house-of-the-dragon':                   'Matt Smith',
  'silo':                                  'Rebecca Ferguson',
  'for-all-mankind':                       'Joel Kinnaman',
  'slow-horses':                           'Gary Oldman',
  'bad-sisters':                           'Sharon Horgan',
  'beef':                                  'Steven Yeun',
  'mr-robot':                              'Rami Malek',
  'peaky-blinders':                        'Cillian Murphy',
  'westworld':                             'Evan Rachel Wood',
  'the-americans':                         'Keri Russell',
  'mad-men':                               'Jon Hamm',
  'lost':                                  'Matthew Fox',
  'the-shield':                            'Michael Chiklis',
  'house':                                 'Hugh Laurie',
  'dexter':                                'Michael C. Hall',
  'arrested-development':                  'Jason Bateman',
  'bojack-horseman':                       'Will Arnett',
  'rick-and-morty':                        'Justin Roiland',
  'house-of-cards':                        'Kevin Spacey',
  'shameless':                             'William H. Macy',
  'watchmen':                              'Regina King',
  'the-pacific':                           'James Badge Dale',
  'orphan-black':                          'Tatiana Maslany',
  'the-good-wife':                         'Julianna Margulies',
  'bates-motel':                           'Vera Farmiga',
  'american-horror-story':                 'Evan Peters',
  'american-crime-story':                  'Sterling K. Brown',
  'big-little-lies':                       'Nicole Kidman',
  'downton-abbey':                         'Hugh Bonneville',
  'the-leftovers':                         'Justin Theroux',
  'happy-valley':                          'Sarah Lancashire',
  'how-to-get-away-with-murder':           'Viola Davis',
  'empire':                                'Taraji P. Henson',
  'lucifer':                               'Tom Ellis',
  'the-walking-dead':                      'Andrew Lincoln',
  'justified':                             'Timothy Olyphant',
  'the-night-of':                          'Riz Ahmed',
  'black-bird':                            'Taron Egerton',
  'the-outsider':                          'Ben Mendelsohn',
  'the-undoing':                           'Nicole Kidman',
  'the-umbrella-academy':                  'Elliot Page',
  'outer-range':                           'Josh Brolin',
  'station-eleven':                        'Mackenzie Davis',
  'twin-peaks':                            'Kyle MacLachlan',
  'the-x-files':                           'David Duchovny',
  '24':                                    'Kiefer Sutherland',
  'friends':                               'Jennifer Aniston',
  'the-big-bang-theory':                   'Jim Parsons',
  'the-office':                            'Steve Carell',
  'the-it-crowd':                          'Chris O\'Dowd',
  'the-expanse':                           'Steven Strait',
  'battlestar-galactica':                  'Edward James Olmos',
  'firefly':                               'Nathan Fillion',
  'buffy-the-vampire-slayer':              'Sarah Michelle Gellar',
  'angel':                                 'David Boreanaz',
  'the-100':                               'Eliza Taylor',
  'the-originals':                         'Joseph Morgan',
  'the-vampire-diaries':                   'Nina Dobrev',
  'grimm':                                 'David Giuntoli',
  'once-upon-a-time':                      'Jennifer Morrison',
  'smallville':                            'Tom Welling',
  'castle':                                'Nathan Fillion',
  'bones':                                 'Emily Deschanel',
  'monk':                                  'Tony Shalhoub',
  'white-collar':                          'Matt Bomer',
  'burn-notice':                           'Jeffrey Donovan',
  'leverage':                              'Timothy Hutton',
  'ncis':                                  'Mark Harmon',
  'criminal-minds':                        'Matthew Gray Gubler',
  'elementary':                            'Jonny Lee Miller',
  'the-mentalist':                         'Simon Baker',
  'lie-to-me':                             'Tim Roth',
  'suits':                                 'Gabriel Macht',
  'chuck':                                 'Zachary Levi',
  'tom-clancy-s-jack-ryan':               'John Krasinski',
  'reacher':                               'Alan Ritchson',
  'the-night-agent':                       'Gabriel Basso',
  'the-terminal-list':                     'Chris Pratt',
  'the-gentlemen':                         'Theo James',
  'cobra-kai':                             'William Zabka',
  'yellowjackets':                         'Melanie Lynskey',
  'outer-banks':                           'Chase Stokes',
  'you':                                   'Penn Badgley',
  'riverdale':                             'KJ Apa',
  'pretty-little-liars':                   'Lucy Hale',
  'teen-wolf':                             'Tyler Posey',
  'gossip-girl':                           'Blake Lively',
  'desperate-housewives':                  'Teri Hatcher',
  'sex-and-the-city':                      'Sarah Jessica Parker',
  'glee':                                  'Lea Michele',
  'the-sinner':                            'Jessica Biel',
  'the-killing':                           'Mireille Enos',
  'the-fall':                              'Gillian Anderson',
  'bodyguard':                             'Richard Madden',
  'broadchurch':                           'Olivia Colman',
  'the-night-manager':                     'Tom Hiddleston',
  'good-omens':                            'David Tennant',
  'shadow-and-bone':                       'Jessie Mei Li',
  'the-wheel-of-time':                     'Rosamund Pike',
  'taboo':                                 'Tom Hardy',
  'penny-dreadful':                        'Eva Green',
  'banshee':                               'Antony Starr',
  'black-sails':                           'Toby Stephens',
  'deadwood':                              'Timothy Olyphant',
  'six-feet-under':                        'Peter Krause',
  'weeds':                                 'Mary-Louise Parker',
  'the-oa':                                'Brit Marling',
  'the-haunting-of-hill-house':            'Michiel Huisman',
  'midnight-mass':                         'Hamish Linklater',
  'the-fall-of-the-house-of-usher':        'Bruce Greenwood',
  'freaks-and-geeks':                      'Linda Cardellini',
  'mr-bean':                               'Rowan Atkinson',
  'after-life':                            'Ricky Gervais',
  '1883':                                  'Tim McGraw',
  '1899':                                  'Emily Beecham',
  'alice-in-borderland':                   'Kento Yamazaki',
  'lupin':                                 'Omar Sy',
  'emily-in-paris':                        'Lily Collins',
  'nine-perfect-strangers':               'Nicole Kidman',
  'from':                                  'Harold Perrineau',
  'sense8':                                'Doona Bae',
};

const pool = JSON.parse(readFileSync(OUT_PATH, 'utf-8'));

let enriched = 0;
for (const show of pool) {
  if (!show.topEpisodeLead) {
    const actor = LEAD_ACTOR_MAP[show.id] || null;
    if (actor) {
      show.topEpisodeLead = actor;
      enriched++;
    }
  }
}

writeFileSync(OUT_PATH, JSON.stringify(pool, null, 2), 'utf-8');
console.log(`Enriched ${enriched} shows with lead actors (${pool.length} total).`);
console.log(`Shows with lead actor: ${pool.filter(s => s.topEpisodeLead).length}`);
console.log(`Shows without lead actor: ${pool.filter(s => !s.topEpisodeLead).length}`);
