#!/usr/bin/env node
/**
 * addTaglines.mjs
 * Enriches puzzle_pool.json with tagline data.
 * Run: node scripts/addTaglines.mjs
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, '../data/puzzle_pool.json');

// Map of show slug ID → tagline
const TAGLINE_MAP = {
  'breaking-bad':                          'All bad things must come to an end.',
  'the-sopranos':                          'Family. Redefined.',
  'the-wire':                              'All the pieces matter.',
  'game-of-thrones':                       'Winter is coming.',
  'the-office':                            'The story of a paper company that lost the plot.',
  'better-call-saul':                      'Everyone starts somewhere.',
  'chernobyl':                             'The true cost of lies.',
  'band-of-brothers':                      'They depended on each other. The world depended on them.',
  'true-detective':                        'Touch darkness and darkness touches you back.',
  'fargo':                                 'A lot can happen in the middle of nowhere.',
  'the-boys':                              'Never meet your heroes.',
  'the-mandalorian':                       'Protect the child.',
  'stranger-things':                       'Every day is a fight against the darkness.',
  'squid-game':                            'Play or die.',
  'succession':                            'Who will succeed?',
  'fleabag':                               'She\'s not the heroine of this story. She knows it.',
  'sherlock':                              'Putting the "high" in high-functioning sociopath.',
  'black-mirror':                          'The future is now.',
  'severance':                             'Work/life separation has never been so complete.',
  'the-white-lotus':                       'Nothing lasts forever.',
  'euphoria':                              'You were never really here.',
  'station-eleven':                        'Remember the world.',
  'ozark':                                 'Something had to give.',
  'peaky-blinders':                        'You have no idea what\'s coming.',
  'westworld':                             'These violent delights have violent ends.',
  'twin-peaks':                            'The owls are not what they seem.',
  'the-americans':                         'One family. Two countries. Infinite lies.',
  'mad-men':                               'Where the truth lies.',
  'lost':                                  'Everything happens for a reason.',
  'the-shield':                            'To protect and serve himself.',
  'house':                                 'Genius. Brilliant. Misanthrope.',
  'dexter':                                'America\'s favorite serial killer.',
  'the-it-crowd':                          'Have you tried turning it off and on again?',
  'arrested-development':                  'The story of a family that lost everything, and the one son who had no choice but to keep them all together.',
  'bojack-horseman':                       'The show about a horse. And a lot of other stuff too.',
  'rick-and-morty':                        'Science. Family. Adventure. Science.',
  'atlanta':                               'An Atlanta rapper and his cousin try to make it in the music industry.',
  'silicon-valley':                        'A place for visionaries.',
  'veep':                                  'Power changes everything.',
  'barry':                                 'A hitman. A dream. A lot of bodies.',
  'ted-lasso':                             'Believe.',
  'the-last-of-us':                        'When you\'re lost in the darkness, look for the light.',
  'andor':                                 'Rebellions are built on hope.',
  'the-crown':                             'Long live the queen.',
  'the-bear':                              'Put in the work.',
  'abbott-elementary':                     'Some teachers were born to teach. Others just needed a job.',
  'what-we-do-in-the-shadows':             'Old habits die hard.',
  'only-murders-in-the-building':          'Everyone\'s a suspect.',
  'money-heist':                           'No rules. One plan.',
  'mr-robot':                              'Control is an illusion.',
  'the-x-files':                           'The truth is out there.',
  '24':                                    'The clock is ticking.',
  'friends':                               'I\'ll be there for you.',
  'shogun':                                'Power is the only truth.',
  'mindhunter':                            'Inside the mind of a killer.',
  'narcos':                                'The operation is over. The legend has just begun.',
  'boardwalk-empire':                      'There\'s a new boss in Atlantic City.',
  'billions':                              'Power. Money. Corruption.',
  'doctor-who':                            'Run.',
  'yellowstone':                           'A constant war.',
  'arcane':                                'Where will you stand when it all falls down?',
  'invincible':                            'What\'s the worst that could happen?',
  'house-of-the-dragon':                   'Fire will reign.',
  'silo':                                  'The truth will surface.',
  'for-all-mankind':                       'All humanity. All the stars.',
  'slow-horses':                           'Britain\'s most unwanted.',
  'bad-sisters':                           'Some families drive you to murder.',
  'beef':                                  'Road rage. Life changing.',
  'the-marvelous-mrs-maisel':              'She\'s got a lot of guts.',
  'hacks':                                 'Don\'t call it a comeback.',
  'heroes':                                'Save the cheerleader. Save the world.',
  'person-of-interest':                    'You are being watched.',
  'two-and-a-half-men':                    'One house. Two men. One impossible kid.',
  'seinfeld':                              'A show about nothing.',
  'fallout':                               'War. War never changes.',
  'sons-of-anarchy':                       'Blood in. Blood out.',
  'one-piece':                             'Dreams never die.',
  '13-reasons-why':                        'Your story isn\'t over.',
  'orange-is-the-new-black':               'You don\'t know the half of it.',
  'hannibal':                              'What are you hungry for?',
  'the-handmaid-s-tale':                   'Her name was Offred. She resisted.',
  'reacher':                               'The law doesn\'t protect them. He does.',
  'scrubs':                                'Life is short. Recovery is long.',
  'its-always-sunny-in-philadelphia':      'Always be closing.',
  'it-s-always-sunny-in-philadelphia':     'Always be closing.',
  'futurama':                              'Welcome to the world of tomorrow!',
  'new-girl':                              'She can handle anything. Except herself.',
  'gotham':                                'Before Batman, there was Gotham.',
  'the-end-of-the-f-ing-world':            'Two teenagers. One dead end.',
  'fullmetal-alchemist-brotherhood':       'One is all. All is one.',
  'gossip-girl':                           'You know you love me.',
  'rome':                                  'Power. Ambition. Murder.',
  'altered-carbon':                        'Your body is just a sleeve.',
  'that-70s-show':                         'The show that put the \'70s in perspective.',
  'outlander':                             'An epic love story spanning time itself.',
  'californication':                       'He writes what he knows.',
  'tom-clancy-s-jack-ryan':               'Not your average analyst.',
  'baby-reindeer':                         'It started with a free pint.',
  'the-last-kingdom':                      'Destiny is all.',
  'entourage':                             'Hollywood\'s most promising actor. And his crew.',
  '3-body-problem':                        'The universe is not what it seems.',
  'this-is-us':                            'Every family has a story.',
  'gilmore-girls':                         'Life\'s short. Talk fast.',
  'archer':                                'The world\'s most dangerous secret agent. And he knows it.',
  'gravity-falls':                         'Not all is as it seems.',
  'spartacus':                             'Blood and sand.',
  'the-punisher':                          'One man. One mission. No mercy.',
  'the-sandman':                           'All your dreams come true.',
  'demon-slayer-kimetsu-no-yaiba':         'To become a Demon Slayer, you must be willing to die.',
  'naruto-shippuden':                      'Believe it.',
  'planet-earth':                          'See our world as you\'ve never seen it before.',
  'planet-earth-ii':                       'The world comes to life.',
  'love-death-robots':                     'Stories from the edge of imagination.',
  'the-falcon-and-the-winter-soldier':     'One legacy. Two heroes.',
  'moon-knight':                           'The truth lies in the dark.',
  'obi-wan-kenobi':                        'The greatest student becomes the greatest teacher.',
  'hawkeye':                               'The city is his. If he can keep it.',
  'obi-wan-kenobi':                        'You can change your name, but the Force will find you.',
  'jujutsu-kaisen':                        'The strongest curse vs. the strongest sorcerer.',
  'hunter-x-hunter':                       'Follow your dreams. Even into danger.',
  'pretty-little-liars':                   'They know everything.',
  'teen-wolf':                             'Some guys have all the luck.',
  'the-gentlemen':                         'Crime pays. Especially for gentlemen.',
  'dragon-ball-z':                         'The greatest fights in the universe.',
  'once-upon-a-time':                      'Every story has a beginning.',
  'the-last-dance':                        'One last run.',
  'one-punch-man':                         'He worked too hard.',
  'scam-1992-the-harshad-mehta-story':     'He made the market dance to his tune.',
  'sh-gun':                                'Power is the only truth.',
  'agents-of-s-h-i-e-l-d':               'Not all heroes are super.',
  'monster':                               'What makes a monster?',
  'peacemaker':                            'Peace. At any cost.',
  'yellowjackets':                         'They survived the crash. The hunger was just beginning.',
  'nine-perfect-strangers':               'A retreat from reality.',
  'the-last-dance':                        'One team. One city. One last shot.',
  'outer-banks':                           'The chase is on.',
  'cobra-kai':                             'Strike first. Strike hard. No mercy.',
  'you':                                   'Love hurts.',
  'the-haunting-of-hill-house':            'Some houses are alive.',
  'midnight-mass':                         'Faith can move mountains.',
  'wednesday':                             'Don\'t lose your head.',
  'the-queen-s-gambit':                    'Her weapon of choice? Her mind.',
  'the-witcher':                           'The world doesn\'t need a hero. It needs a monster.',
  'vikings':                               'New worlds will be conquered.',
  'prison-break':                          'Break in. Break out.',
  'the-good-place':                        'Welcome! Everything is fine.',
  'community':                             'Study hard. Party hard. Hardly study.',
  'parks-and-recreation':                  'Government of the people, by the people, for the people.',
  'brooklyn-nine-nine':                    'The precinct\'s finest.',
  'shameless':                             'No shame in being shameless.',
  'justified-city-primeval':               'A new city. The same man.',
  'the-umbrella-academy':                  'Not your ordinary family.',
  'the-witcher-s2':                        'The world doesn\'t need a hero. It needs a monster.',
  'bridgerton':                            'Dear reader...',
  'the-diplomat':                          'Save the world. Avoid the husband.',
  'bad-sisters':                           'Some families drive you to murder.',
  'beef':                                  'Road rage. Life changing.',
  'say-nothing':                           'Everyone has a price.',
  'the-penguin':                           'Crime. Power. Family.',

  'the-blacklist':                         'Nothing is what it seems.',
  'the-terror':                            'In the arctic, every enemy is invisible.',
  'narcos-mexico':                         'The empire strikes back.',
  'malcolm-in-the-middle':                 'The middle child rules!',
  'bridgerton':                            'Dear reader...',
  'the-flash':                             'Life is locomotion.',
  'the-following':                         'You can\'t stop what\'s coming.',
  'skins':                                 'This is your life.',
  'the-penguin':                           'Crime. Power. Family.',
  'the-lord-of-the-rings-the-rings-of-power': 'The fate of all Middle-earth is at stake.',
  'the-diplomat':                          'Save the world. Avoid the husband.',
  'the-old-man':                           'There\'s no escaping your past.',
  'killing-eve':                           'Killing is easy.',
  'luther':                                'He saves lives. He breaks rules.',
  'the-fall':                              'Hunt or be hunted.',
  'true-blood':                            'All will be revealed.',
  'homeland':                              'The CIA\'s most valuable asset. The agency\'s most dangerous threat.',
  'house-of-cards':                        'There are two kinds of pain.',
  'shameless':                             'No shame in being shameless.',
  'watchmen':                              'Who watches the watchmen?',
  'the-pacific':                           'Hell is not a place. It\'s an experience.',
  'nurse-Jackie':                          'She\'s one tough cookie.',
  'damages':                               'Trust no one.',
  'dark':                                  'The beginning is the end.',
  'orphan-black':                          'These women are cloning it.',
  'american-horror-story':                 'Fear starts here.',
  'the-good-wife':                         'She\'s one of the good ones.',
  'bates-motel':                           'A boy\'s best friend is his mother.',
  '30-rock':                               '30 Rockefeller Plaza. It\'s not just an address.',
  'its-always-sunny-in-philadelphia':      'Always be closing.',
  'american-crime-story':                  'America\'s guiltiest pleasure.',
  'big-little-lies':                       'Big love. Bigger lies.',
  'downton-abbey':                         'Tradition has its privileges.',
  'the-leftovers':                         'There are no answers.',
  'happy-valley':                          'Everyone has a secret.',
  'how-to-get-away-with-murder':           'Some laws were meant to be broken.',
  'lucifer':                               'The devil made me do it.',
  'the-walking-dead':                      'Fight the dead. Fear the living.',
  'justified':                             'Down here, justice comes in all calibers.',
  'daredevil':                             'Justice is blind.',
  'jessica-jones':                         'Smile. It could be worse.',
  'the-night-of':                          'Every crime has a witness.',
  'black-bird':                            'The real crime started after the arrest.',
  'the-umbrella-academy':                  'Not your ordinary family.',
  'outer-range':                           'The border between worlds.',
  'the-undoing':                           'Marriage of convenience? No, of lies.',
  'mare-of-easttown':                      'In this town, everyone has a secret.',
  'perry-mason':                           'The truth will cost you everything.',
  'the-outsider':                          'Evil wears many faces.',
  'prison-break':                          'Break in. Break out.',
  'the-queen-s-gambit':                    'Her weapon of choice? Her mind.',
  'vikings':                               'New worlds will be conquered.',
  'the-witcher':                           'The world doesn\'t need a hero. It needs a monster.',
  'modern-family':                         'Family. It\'s complicated.',
  'suits':                                 'Success isn\'t everything. Winning is.',
  'supernatural':                          'Saving people. Hunting things. The family business.',
  'wednesday':                             'Don\'t lose your head.',
  'death-note':                            'Justice. Or murder?',
  'loki':                                  'Glorious purpose.',
  'the-simpsons':                          'An American family. Somewhat.',
  'south-park':                            'Not for children.',
  'avatar-the-last-airbender':             'The fate of the world rests on the shoulders of a 12-year-old.',
  'brooklyn-nine-nine':                    'The precinct\'s finest. And Jake Peralta.',
  'wandavision':                           'A new vision of family life.',
  'sex-education':                         'Growing up is complicated.',
  'family-guy':                            'Family is everything. Almost.',
  'how-i-met-your-mother':                 'It\'s going to be legen... wait for it... dary.',
  'the-big-bang-theory':                   'Smart is the new sexy.',
  'attack-on-titan':                       'The last of humanity fights for survival.',
  'arrow':                                 'You have failed this city.',
  'grey-s-anatomy':                        'It\'s a beautiful day to save lives.',
  'empire':                                'Success has a price.',
  'the-good-place':                        'Welcome! Everything is fine.',
  'community':                             'Study hard. Party hard. Hardly study.',
  'parks-and-recreation':                  'We the people have found our parks.',
  'house-of-cards-us':                     'There are two kinds of pain.',
  'miniseries-chernobyl':                  'The true cost of lies.',
  'the-terror':                            'In the arctic, every enemy is invisible.',
  'sharp-objects':                         'What lies beneath the skin.',
  'fleabag':                               'She\'s not the hero of her own story. She knows it.',
  'the-haunting-of-hill-house':            'Some houses are alive.',
  'midnight-mass':                         'Faith can move mountains.',
  'the-haunting-of-bly-manor':             'Some loves outlast a lifetime.',
  'the-act':                               'The truth is stranger than fiction.',
  'unbelievable':                          'The truth was right there.',
  'mare-of-easttown':                      'In this town, everyone has a secret.',
  'yellowjackets':                         'They survived the crash. It only got darker from there.',
  'squid-game':                            'Play or die.',
  'see':                                   'In a world without sight, one sense rules all.',
  'foundation':                            'The future of civilization rests on one man\'s vision.',
  'the-expanse':                           'Some things are worth dying for.',
  'battlestar-galactica':                  'So say we all.',
  'the-100':                               'Life is not about surviving. It\'s about living.',
  'firefly':                               'You can\'t take the sky from me.',
  'buffy-the-vampire-slayer':              'In every generation, one is chosen.',
  'angel':                                 'The vampire with a soul.',
  'the-vampire-diaries':                   'They were here first.',
  'the-originals':                         'Family is power.',
  'legacies':                              'One generation of heroes ends. Another begins.',
  'the-100':                               'Earth isn\'t just a legend.',
  'castle':                                'He\'s murder. She\'s mayhem.',
  'law-order-svu':                         'Some crimes demand a special response.',
  'law-order':                             'In the criminal justice system...',
  'criminal-minds':                        'Getting into the minds of killers.',
  'ncis':                                  'It\'s not just a job. It\'s an adventure.',
  'csi-crime-scene-investigation':         'The evidence doesn\'t lie.',
  'bones':                                 'Every body tells a story.',
  'fringe':                                'What do you think is possible?',
  'the-mentalist':                         'He\'s not psychic. He just sees things.',
  'monk':                                  'The defective detective.',
  'white-collar':                          'Con man. FBI consultant. Con man.',
  'burn-notice':                           'A burned spy. A trigger-happy ex-girlfriend. One hell of a team.',
  'leverage':                              'The rich and powerful take what they want.',
  'suits':                                 'Success isn\'t everything. Winning is.',
  'suits-la':                              'West Coast justice.',
  'the-crown-s1':                          'Serve. Reign. Endure.',
  'halston':                               'Fashion is everything.',
  'the-plot-against-america':              'What if it happened here?',
  'i-know-this-much-is-true':              'Two brothers. One destiny.',
  'scenes-from-a-marriage':               'Love hurts.',
  'industry':                              'Play the long game.',
  'succession-s1':                         'Who will succeed?',
  'the-rehearsal':                         'Practice makes perfect. Or does it?',
  'the-bear-s2':                           'Put in the work.',
  'the-diplomat-s2':                       'Diplomacy. It\'s complicated.',
  'the-penguin':                           'Crime. Power. Family.',
  'say-nothing':                           'Everyone has a price.',
  'slow-horses':                           'Welcome to Slough House.',
  'physical':                              'Sweat is just fat crying.',
  'disclaimer':                            'Some truths are better left untold.',
  'bad-sisters':                           'Sisters before misters. Even murder.',
  'the-fall-season-2':                     'The chase continues.',
  'bloodline':                             'We\'re not bad people. But we did a bad thing.',
  'city-on-a-hill':                        'Power. Corruption. Justice.',
  'the-newsroom':                          'Make television matter again.',
  'the-comeback':                          'She\'s back.',
  'the-plot-against-america':              'What if it happened here?',
  'new-amsterdam':                         'Change the rules. Save lives.',
  'revenge':                               'Revenge is a dish best served cold.',
  'show-me-a-hero':                        'The real story of a city at war with itself.',
  'spin-city':                             'The mayor has left the building.',
  'saving-grace':                          'One tough cop. One last-chance angel.',
  'in-treatment':                          'Every mind has its breaking point.',
  'madam-secretary':                       'It\'s a tough world. Good thing she\'s tougher.',
  'the-good-fight':                        'The fight isn\'t over.',
  'billions-s2':                           'More money. More problems.',
  'outer-banks':                           'The chase is on.',
  'cobra-kai':                             'Strike first. Strike hard. No mercy.',
  'sex-life':                              'Every fantasy has a price.',
  'ginny-georgia':                         'Like mother, like daughter. Kind of.',
  'you':                                   'Love hurts.',
  'ozark-s4':                              'There\'s no clean way out.',
  'the-witcher-s2':                        'The world doesn\'t need a hero. It needs a monster.',
  'bridgerton-s2':                         'Dear reader... it\'s getting complicated.',
  'the-watcher':                           'Home is where the horror is.',
  'dahmer':                                'Monster: The Jeffrey Dahmer Story',
  'wednesday-s1':                          'Don\'t lose your head.',
  'beef':                                  'Road rage. Life changing.',
  'the-bear-s1':                           'The kitchen is a battlefield.',
  'the-last-of-us-s1':                     'When you\'re lost in the darkness, look for the light.',
  'the-crown-s5':                          'What does it cost to be queen?',
  'succession-s4':                         'This is the end.',
  'andor-s1':                              'Rebellions are built on hope.',
  'house-of-the-dragon-s2':               'The war for the throne has begun.',
  'squid-game-s2':                         'The game is back.',
  'shogun-s1':                             'Power is the only truth.',
  'the-penguin-s1':                        'Crime. Power. Family.',
  'say-nothing-s1':                        'Everyone has a price.',
  'silo-s1':                               'The truth will surface.',
  'for-all-mankind-s4':                    'All humanity. All the stars.',
  'slow-horses-s3':                        'Britain\'s most unwanted.',
  'bad-sisters-s2':                        'The Garveys are back.',
  'the-diplomat-s1':                       'Save the world. Avoid the husband.',
  'the-old-man-s2':                        'There\'s no escaping your past.',
  'nine-perfect-strangers':                'A retreat from reality.',
  'under-the-banner-of-heaven':            'God\'s will. Man\'s evil.',
  'the-night-of-s1':                       'Every crime has a witness.',
  'the-terror-s1':                         'In the arctic, every enemy is invisible.',
  'the-outsider-s1':                       'Evil wears many faces.',
  'big-little-lies-s2':                    'The lies continue.',
  'sharp-objects-miniseries':              'What lies beneath the skin.',

  // Additional shows
  'schitt-s-creek':                        'Riches to rags. Family first.',
  'sense8':                                'Eight minds. One soul.',
  'bodyguard':                             'Who\'s protecting who?',
  'from':                                  'There\'s no way out.',
  'after-life':                            'Finding a reason to live.',
  'cowboy-bebop':                          'See you, space cowboy.',
  'six-feet-under':                        'Life is a work in progress.',
  'curb-your-enthusiasm':                  'No hugging. No learning. Zero manners.',
  'riverdale':                             'Not your father\'s Archie.',
  'freaks-and-geeks':                      'A different kind of high school.',
  'naruto':                                'Believe it!',
  'the-wheel-of-time':                     'The wheel turns. The ages come and pass.',
  'taboo':                                 'Some things should never be disturbed.',
  'glee':                                  'Don\'t stop believing.',
  '1883':                                  'Before Yellowstone.',
  'what-if':                               'A different kind of universe.',
  'sex-and-the-city':                      'Four women. Eight hundred shoes.',
  'lupin':                                 'The master of disguise.',
  'chuck':                                 'Not the spy you expected.',
  'fear-the-walking-dead':                 'Dead don\'t discriminate.',
  'desperate-housewives':                  'Everyone has a secret.',
  'the-fresh-prince-of-bel-air':           'The one and only Will Smith.',
  'the-night-agent':                       'Stay on the line.',
  'the-sinner':                            'Why did she do it?',
  'smallville':                            'Not your father\'s Superman.',
  'dexter-new-blood':                      'Evil never dies.',
  'mr-bean':                               'There\'s only one Mr. Bean.',
  'the-legend-of-korra':                   'The next chapter begins.',
  'the-morning-show':                      'What wakes America.',
  'star-trek-the-next-generation':         'The mission continues.',
  'iron-fist':                             'The iron fist strikes.',
  'luke-cage':                             'Power man.',
  'star-trek-discovery':                   'The final frontier, rediscovered.',
  'gen-v':                                 'Young blood. Old games.',
  'banshee':                               'Fake it till you make it.',
  'young-sheldon':                         'Before the Big Bang Theory.',
  'alice-in-borderland':                   'Play or die.',
  'emily-in-paris':                        'Love. Fashion. Croissants.',
  'broadchurch':                           'A murder. A community. A secret.',
  'grimm':                                 'Some fairy tales are real.',
  'ahsoka':                                'A new journey begins.',
  'penny-dreadful':                        'Where the darkest nightmare meets the deepest desire.',
  'top-gear':                              'More power.',
  'batman-the-animated-series':            'The dark knight returns.',
  'lie-to-me':                             'He can read you like a book.',
  'supergirl':                             'The girl of steel.',
  'the-fall-of-the-house-of-usher':        'Darkness descends.',
  'the-killing':                           'Who killed Rosie Larsen?',
  'the-night-manager':                     'Everyone plays a game.',
  'adventure-time':                        'Mathematical!',
  'ms-marvel':                             'A hero emerges.',
  'the-good-doctor':                       'He sees what others miss.',
  'deadwood':                              'Gold. Power. Corruption.',
  'the-oa':                                'Every story has a beginning.',
  'the-terminal-list':                     'No witness. No mercy.',
  'elementary':                            'Watson. Sherlock. Unpredictable.',
  'the-defenders':                         'Four heroes. One city.',
  'black-sails':                           'The origins of the most feared pirate in history.',
  'shadow-and-bone':                       'The sun summoner rises.',
  'good-omens':                            'Heaven vs. Hell. Neither wins.',
  'weeds':                                 'One plant. One problem.',
  '1899':                                  'Everything is connected.',
  'cyberpunk-edgerunners':                 'Going out in style.',
  'spongebob-squarepants':                 'Are you ready, kids?',
  'vinland-saga':                          'War never ends. Neither does ambition.',
  'the-sinner':                            'Why did she do it?',
  'star-wars-the-clone-wars':              'An epic saga continues.',
  'law-order-special-victims-unit':        'Some crimes demand a special response.',
  'the-book-of-boba-fett':                 'The galaxy\'s most feared bounty hunter is back.',
  'she-hulk-attorney-at-law':              'She\'s got this. Probably.',
  'the-acolyte':                           'In the shadows of the Republic.',
  'ms-marvel':                             'A new hero for a new era.',
  'peacemaker':                            'Peace. At any cost.',
  'cosmos-a-spacetime-odyssey':            'A space-time odyssey.',
  'battlestar-galactica':                  'So say we all.',
  'buffy-the-vampire-slayer':              'In every generation, one is chosen.',
  'angel':                                 'The vampire with a soul.',
  'firefly':                               'You can\'t take the sky from me.',
  'gilmore-girls':                         'Life\'s short. Talk fast.',
  'this-is-us':                            'Every family has a story.',
  'the-good-fight':                        'The fight isn\'t over.',
  'the-originals':                         'Family is power.',
  'the-vampire-diaries':                   'Love never dies.',
  'outer-banks':                           'The chase is on.',
  'yellowjackets':                         'They survived the crash. The hunger just began.',
  'cobra-kai':                             'Strike first. Strike hard. No mercy.',
  'nine-perfect-strangers':               'A retreat from reality.',
  'dexter-resurrection':                   'He\'s back. Again.',
  'pluribus':                              'The story of us.',
  'dhindora':                              'Khujli uski, zimedaari humari.',
  'the-day-of-the-jackal':                 'The world\'s deadliest assassin.',
  'the-morning-show':                      'What wakes America.',
  'station-eleven':                        'Remember the world.',
  'the-expanse':                           'Some things are worth dying for.',
  'foundation':                            'The future of civilization rests on one man\'s vision.',
  'battlestar-galactica':                  'So say we all.',
  'see':                                   'In a world without sight, one sense rules all.',
  'for-all-mankind':                       'All humanity. All the stars.',
  'silo':                                  'The truth will surface.',
  'nurse-jackie':                          'She\'s one tough cookie.',
  'the-fall':                              'Hunt or be hunted.',
  'bodyguard':                             'Who\'s protecting who?',
  'the-night-manager':                     'Everyone plays a game.',
  'broadchurch':                           'A murder. A community. A secret.',
  'penny-dreadful':                        'Where the darkest nightmare meets the deepest desire.',
  'banshee':                               'Fake it till you make it.',
  'black-sails':                           'The origins of the most feared pirate in history.',
  'deadwood':                              'Gold. Power. Corruption.',
  'entourage':                             'Hollywood\'s most promising actor. And his crew.',
  '3-body-problem':                        'The universe is not what it seems.',
  'the-gentlemen':                         'Crime pays. Especially for gentlemen.',
  'baby-reindeer':                         'It started with a free pint.',
  'the-last-kingdom':                      'Destiny is all.',
  'the-terminal-list':                     'No witness. No mercy.',
  'the-sandman':                           'All your dreams come true.',
  'spartacus':                             'Blood and sand.',
  'the-end-of-the-f-ing-world':            'Two teenagers. One dead end.',
  'reacher':                               'The law doesn\'t protect them. He does.',
  'the-handmaid-s-tale':                   'Her name was Offred. She resisted.',
  'hannibal':                              'What are you hungry for?',
  'orange-is-the-new-black':               'You don\'t know the half of it.',
  '13-reasons-why':                        'Your story isn\'t over.',
  'sons-of-anarchy':                       'Blood in. Blood out.',
  'fallout':                               'War. War never changes.',
  'the-haunting-of-hill-house':            'Some houses are alive.',
  'scrubs':                                'Life is short. Recovery is long.',
  'the-umbrella-academy':                  'Not your ordinary family.',
  'fringe':                                'What do you think is possible?',
  'new-girl':                              'She can handle anything. Except herself.',
  'gotham':                                'Before Batman, there was Gotham.',
  'once-upon-a-time':                      'Every story has a beginning.',
  'community':                             'Study hard. Party hard. Hardly study.',
  'parks-and-recreation':                  'Government of the people, by the people.',
  'the-100':                               'Life is not about surviving. It\'s about living.',
  'moon-knight':                           'The truth lies in the dark.',
  'the-falcon-and-the-winter-soldier':     'One legacy. Two heroes.',
  'hawkeye':                               'The city is his. If he can keep it.',
  'the-penguin':                           'Crime. Power. Family.',
  'wandavision':                           'A new vision of family life.',
  'sex-education':                         'Growing up is complicated.',
  'wednesday':                             'Don\'t lose your head.',
  'you':                                   'Love hurts.',
  'the-vampire-diaries':                   'Love never dies.',
  'the-witcher':                           'The world doesn\'t need a hero. It needs a monster.',
  'prison-break':                          'Break in. Break out.',
  'the-queen-s-gambit':                    'Her weapon of choice? Her mind.',
  'vikings':                               'New worlds will be conquered.',
  'modern-family':                         'Family. It\'s complicated.',
  'supernatural':                          'Saving people. Hunting things.',
  'narcos':                                'The operation is over. The legend begins.',
  'attack-on-titan':                       'The last of humanity fights for survival.',
  'fullmetal-alchemist-brotherhood':       'One is all. All is one.',
  'demon-slayer-kimetsu-no-yaiba':         'To become a demon slayer, you must be willing to die.',
  'naruto-shippuden':                      'Believe it!',
  'death-note':                            'Justice. Or murder?',
  'one-piece':                             'Dreams never die.',
  'jujutsu-kaisen':                        'The strongest curse vs. the strongest sorcerer.',
  'gossip-girl':                           'You know you love me.',
  'pretty-little-liars':                   'They know everything.',
  'teen-wolf':                             'Some guys have all the luck.',
  'riverdale':                             'Not your father\'s Archie.',
  'that-70s-show':                         'The show that put the \'70s in perspective.',
  'outlander':                             'An epic love story spanning time itself.',
  'californication':                       'He writes what he knows.',
  'glee':                                  'Don\'t stop believing.',
  'the-fresh-prince-of-bel-air':           'Will Smith. Before the movies.',
  'desperate-housewives':                  'Everyone has a secret.',
  'sex-and-the-city':                      'Four women. Eight hundred shoes.',
  'smallville':                            'Not your father\'s Superman.',
  'gilmore-girls':                         'Life\'s short. Talk fast.',
  'this-is-us':                            'Every family has a story.',
  'young-sheldon':                         'Before the Big Bang Theory.',
  'lupin':                                 'The master of disguise.',
  'emily-in-paris':                        'Love. Fashion. Croissants.',
  'alice-in-borderland':                   'Play or die.',
  '1899':                                  'Everything is connected.',
  'sense8':                                'Eight minds. One soul.',
  'schitt-s-creek':                        'Riches to rags. Family first.',
  'mr-bean':                               'There\'s only one Mr. Bean.',
  'the-last-dance':                        'One last run.',
  'curb-your-enthusiasm':                  'No hugging. No learning. Zero manners.',
  'after-life':                            'Finding a reason to live.',
  'scam-1992-the-harshad-mehta-story':     'He made the market dance to his tune.',
  'cowboy-bebop':                          'See you, space cowboy.',
  'the-wheel-of-time':                     'The wheel turns.',
  'taboo':                                 'Some things should never be disturbed.',
  'grimm':                                 'Some fairy tales are real.',
  'the-oa':                                'Every story has a beginning.',
  'dark':                                  'The beginning is the end.',
  'one-punch-man':                         'He worked too hard.',
  'hunter-x-hunter':                       'Follow your dreams. Even into danger.',
  'monster':                               'What makes a monster?',
  'vinland-saga':                          'War never ends. Neither does ambition.',
  'spongebob-squarepants':                 'Are you ready, kids?',
  'gravity-falls':                         'Not all is as it seems.',
  'adventure-time':                        'Mathematical!',
  'batman-the-animated-series':            'Gotham\'s dark knight.',
  'top-gear':                              'More power.',
  'cosmos-a-spacetime-odyssey':            'A space-time odyssey.',
  'star-trek-the-next-generation':         'The mission continues.',
  'star-trek-discovery':                   'The final frontier, rediscovered.',
  'star-wars-the-clone-wars':              'An epic saga continues.',
  'the-acolyte':                           'In the shadows of the Republic.',
  'ahsoka':                                'A new journey begins.',
};

const pool = JSON.parse(readFileSync(OUT_PATH, 'utf-8'));

let enriched = 0;
for (const show of pool) {
  const tagline = TAGLINE_MAP[show.id] || null;
  if (tagline && !show.tagline) {
    show.tagline = tagline;
    enriched++;
  } else if (!show.tagline) {
    show.tagline = null;
  }
}

writeFileSync(OUT_PATH, JSON.stringify(pool, null, 2), 'utf-8');
console.log(`Enriched ${enriched} shows with taglines (${pool.length} total).`);
console.log(`Shows with taglines: ${pool.filter(s => s.tagline).length}`);
console.log(`Shows without taglines: ${pool.filter(s => !s.tagline).length}`);
