#!/usr/bin/env node
/**
 * fillAllData.mjs
 * ---------------
 * Fills in topEpisodeLead and tagline for every show in puzzle_pool.json
 * that is missing one or both. Never overwrites existing data.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, '../data/puzzle_pool.json');

// ── Lead Actor Map ─────────────────────────────────────────────────────────────
const LEAD = {
  // ── A ──
  'abbott-elementary': 'Quinta Brunson',
  'agent-carter': 'Hayley Atwell',
  'agatha-all-along': 'Kathryn Hahn',
  'alcatraz': 'Sam Neill',
  'alias': 'Jennifer Garner',
  'alias-grace': 'Sarah Gadon',
  'alf': 'Paul Fusco',
  'ally-mcbeal': 'Calista Flockhart',
  'alphas': 'David Strathairn',
  'american-gods': 'Ricky Whittle',
  'american-horror-stories': 'Billie Lourd',
  'american-primeval': 'Taylor Kitsch',
  'american-vandal': 'Tyler Alvarez',
  'anatomy-of-a-scandal': 'Sienna Miller',
  'and-just-like-that': 'Sarah Jessica Parker',
  'angels-in-america': 'Al Pacino',
  'anger-management': 'Charlie Sheen',
  'animal-kingdom': 'Ellen Barkin',
  'anne-with-an-e': 'Amybeth McNulty',
  'another-life': 'Katee Sackhoff',
  'aqua-teen-hunger-force': 'Dave Willis',
  'ash-vs-evil-dead': 'Bruce Campbell',
  'awkward': 'Ashley Rickards',
  // ── B ──
  'babylon-5': 'Bruce Boxleitner',
  'bad-monkey': 'Vince Vaughn',
  'ballers': 'Dwayne Johnson',
  'batman': 'Adam West',
  'batman-beyond': 'Will Friedle',
  'batwoman': 'Ruby Rose',
  'baywatch': 'David Hasselhoff',
  'beauty-and-the-beast': 'Kristin Kreuk',
  'beavis-and-butt-head': 'Mike Judge',
  'behind-her-eyes': 'Simona Brown',
  'ben-10': 'Tara Strong',
  'beverly-hills-90210': 'Jason Priestley',
  'big-mouth': 'Nick Kroll',
  'black-books': 'Dylan Moran',
  'black-doves': 'Keira Knightley',
  'black-lightning': 'Cress Williams',
  'black-rabbit': 'Jude Law',
  'black-summer': 'Jaime King',
  'blindspot': 'Jaimie Alexander',
  'blue-bloods': 'Tom Selleck',
  'blue-eye-samurai': 'Maya Erskine',
  'blue-mountain-state': 'Alan Ritchson',
  'bluey': 'David McCormack',
  'bob-s-burgers': 'H. Jon Benjamin',
  'bodies': 'Amaka Okafor',
  'bored-to-death': 'Jason Schwartzman',
  'boston-legal': 'James Spader',
  'boy-meets-world': 'Ben Savage',
  'broad-city': 'Abbi Jacobson',
  // ── C ──
  'call-the-midwife': 'Laura Main',
  'carniv-le': 'Nick Stahl',
  'carnival-row': 'Orlando Bloom',
  'castle-rock': 'André Holland',
  'catdog': 'Jim Cummings',
  'chainsaw-man': 'Ryunosuke Kamiki',
  'chappelle-s-show': 'Dave Chappelle',
  'charmed': 'Alyssa Milano',
  'cheers': 'Ted Danson',
  'chicago-fire': 'Jesse Spencer',
  'chicago-med': 'Nick Gehlfuss',
  'chicago-p-d': 'Jason Beghe',
  'chucky': 'Brad Dourif',
  'citadel': 'Richard Madden',
  'clickbait': 'Zoe Kazan',
  'cold-case': 'Kathryn Morris',
  'colony': 'Josh Holloway',
  'code-geass': 'Jun Fukuyama',
  'columbo': 'Peter Falk',
  'constantine': 'Matt Ryan',
  'continuum': 'Rachel Nichols',
  'cosmos': 'Neil deGrasse Tyson',
  'counterpart': 'J.K. Simmons',
  'courage-the-cowardly-dog': 'Marty Grabstein',
  'cougar-town': 'Courteney Cox',
  'covert-affairs': 'Piper Perabo',
  'crashing': 'Pete Holmes',
  'cross': 'Aldis Hodge',
  'csi-miami': 'David Caruso',
  'csi-ny': 'Gary Sinise',
  'cunk-on-earth': 'Diane Morgan',
  'cursed': 'Katherine Langford',
  // ── D ──
  'da-vinci-s-demons': 'Tom Riley',
  'daisy-jones-the-six': 'Riley Keough',
  'dandadan': 'Natsuki Hanae',
  'dark-angel': 'Jessica Alba',
  'dark-matter': 'Joel Edgerton',
  'dark-winds': 'Zahn McClarnon',
  'daria': 'Tracy Grandstaff',
  'dawson-s-creek': 'James Van Der Beek',
  'dead-like-me': 'Ellen Muth',
  'daredevil-born-again': 'Charlie Cox',
  'defiance': 'Grant Bowler',
  'defending-jacob': 'Chris Evans',
  'derek': 'Ricky Gervais',
  'derry-girls': 'Saoirse-Monica Jackson',
  'devs': 'Nick Offerman',
  'dexter-s-laboratory': 'Christine Cavanaugh',
  'dexter-original-sin': 'Patrick Gibson',
  'dharma-greg': 'Jenna Elfman',
  'dirk-gently-s-holistic-detective-agency': 'Samuel Barnett',
  'disenchantment': 'Abbi Jacobson',
  'dollhouse': 'Eliza Dushku',
  'don-t-trust-the-b-in-apartment-23': 'Krysten Ritter',
  'doom-patrol': 'Matt Bomer',
  'dracula': 'Claes Bang',
  'drake-josh': 'Drake Bell',
  'ducktales': 'David Tennant',
  'dune-prophecy': 'Emily Watson',
  // ── E ──
  'eastbound-down': 'Danny McBride',
  'echo': 'Alaqua Cox',
  'ed-edd-n-eddy': 'Matt Hill',
  'endeavour': 'Shaun Evans',
  'er': 'Anthony Edwards',
  'eric': 'Benedict Cumberbatch',
  'erased': 'Tao Tsuchiya',
  'escape-at-dannemora': 'Benicio del Toro',
  'eureka': 'Colin Ferguson',
  'everybody-hates-chris': 'Tyler James Williams',
  'everybody-loves-raymond': 'Ray Romano',
  // ── F ──
  'f-is-for-family': 'Bill Burr',
  'falling-skies': 'Noah Wyle',
  'farscape': 'Ben Browder',
  'father-ted': 'Dermot Morgan',
  'fate-the-winx-saga': 'Abigail Cowen',
  'feud': 'Susan Sarandon',
  'final-space': 'Olan Rogers',
  'firefly-lane': 'Katherine Heigl',
  'first-kill': 'Sarah Catherine Hook',
  'flashforward': 'Joseph Fiennes',
  'flight-of-the-conchords': 'Jemaine Clement',
  'the-flintstones': 'Alan Reed',
  'fool-me-once': 'Michelle Keegan',
  'forever': 'Maya Rudolph',
  'formula-1-drive-to-survive': 'Will Buxton',
  'foster-s-home-for-imaginary-friends': 'Sean Marquette',
  'four-seasons': 'Steve Carell',
  'fresh-off-the-boat': 'Constance Wu',
  'friday-night-lights': 'Kyle Chandler',
  'frozen-planet': 'David Attenborough',
  'fubar': 'Arnold Schwarzenegger',
  'fuller-house': 'Candace Cameron Bure',
  'fullmetal-alchemist': 'Vic Mignogna',
  'future-man': 'Josh Hutcherson',
  // ── G ──
  'generation-kill': 'Alexander Skarsgård',
  'ghost-whisperer': 'Jennifer Love Hewitt',
  'ghosts': 'Rose McIver',
  'ginny-georgia': 'Brianne Howey',
  'girls': 'Lena Dunham',
  'glow': 'Alison Brie',
  'godless': 'Michelle Dockery',
  'goliath': 'Billy Bob Thornton',
  'good-girls': 'Christina Hendricks',
  'grace-and-frankie': 'Jane Fonda',
  'guillermo-del-toro-s-cabinet-of-curiosities': 'Guillermo del Toro',
  // ── H ──
  'haikyu': 'Ayumu Murase',
  'halt-and-catch-fire': 'Lee Pace',
  'hanna': 'Esme Creed-Miles',
  'hannah-montana': 'Miley Cyrus',
  'harley-quinn': 'Kaley Cuoco',
  'hart-of-dixie': 'Rachel Bilson',
  'haven': 'Emily Rose',
  'hawaii-five-0': 'Alex O\'Loughlin',
  'hazbin-hotel': 'Erika Henningsen',
  'heartstopper': 'Kit Connor',
  'helix': 'Billy Campbell',
  'hell-on-wheels': 'Anson Mount',
  'hemlock-grove': 'Famke Janssen',
  'hercules-the-legendary-journeys': 'Kevin Sorbo',
  'hey-arnold': 'Mason Vale Cotton',
  'high-potential': 'Kaitlin Olson',
  'hijack': 'Idris Elba',
  'his-dark-materials': 'Dafne Keen',
  'home-improvement': 'Tim Allen',
  'homecoming': 'Julia Roberts',
  'hunters': 'Al Pacino',
  // ── I ──
  'i-am-not-okay-with-this': 'Sophia Lillis',
  'i-love-lucy': 'Lucille Ball',
  'icarly': 'Miranda Cosgrove',
  'inside-job': 'Lizzy Caplan',
  'insatiable': 'Debby Ryan',
  'interview-with-the-vampire': 'Jacob Anderson',
  'into-the-badlands': 'Daniel Wu',
  'invasion': 'Sam Neill',
  'inventing-anna': 'Julia Garner',
  'ironheart': 'Dominique Thorne',
  'it-s-a-sin': 'Olly Alexander',
  'it-welcome-to-derry': 'Bill Skarsgård',
  'izombie': 'Rose McIver',
  // ── J ──
  'jackass': 'Johnny Knoxville',
  'jane-the-virgin': 'Gina Rodriguez',
  'jericho': 'Skeet Ulrich',
  'joey': 'Matt LeBlanc',
  'johnny-bravo': 'Jeff Bennett',
  'jojo-s-bizarre-adventure': 'Kensho Ono',
  'jupiter-s-legacy': 'Josh Duhamel',
  'justice-league': 'Phil LaMarr',
  // ── K ──
  'kaos': 'Jeff Goldblum',
  'kaleidoscope': 'Giancarlo Esposito',
  'key-and-peele': 'Keegan-Michael Key',
  'kim-possible': 'Christy Carlson Romano',
  'king-of-the-hill': 'Mike Judge',
  'knight-rider': 'David Hasselhoff',
  'the-kominsky-method': 'Michael Douglas',
  'kyle-xy': 'Matt Dallas',
  // ── L ──
  'landman': 'Billy Bob Thornton',
  'las-vegas': 'Josh Duhamel',
  'last-man-standing': 'Tim Allen',
  'last-week-tonight-with-john-oliver': 'John Oliver',
  'the-last-man-on-earth': 'Will Forte',
  'the-last-ship': 'Eric Dane',
  'law-order': 'Sam Waterston',
  'law-order-criminal-intent': 'Vincent D\'Onofrio',
  'legend-of-the-seeker': 'Craig Horner',
  'legacies': 'Danielle Rose Russell',
  'legion': 'Dan Stevens',
  'lethal-weapon': 'Damon Wayans',
  'life': 'Damian Lewis',
  'life-on-mars': 'John Simm',
  'limitless': 'Jake McDorman',
  'line-of-duty': 'Adrian Dunbar',
  'lioness': 'Zoe Saldana',
  'little-fires-everywhere': 'Reese Witherspoon',
  'little-house-on-the-prairie': 'Melissa Gilbert',
  'living-with-yourself': 'Paul Rudd',
  'lockwood-co': 'Cameron Chapman',
  'locke-key': 'Darby Stanchfield',
  'longmire': 'Robert Taylor',
  'lost-girl': 'Anna Silk',
  'louie': 'Louis C.K.',
  'lovecraft-country': 'Jonathan Majors',
  'love': 'Gillian Jacobs',
  'love-death': 'Elizabeth Olsen',
  // ── M ──
  'macgyver': 'Richard Dean Anderson',
  'mad-about-you': 'Paul Reiser',
  'magnum-p-i': 'Jay Hernandez',
  'maniac': 'Emma Stone',
  'manhunt': 'Tobias Menzies',
  'manifest': 'Melissa Roxburgh',
  'marco-polo': 'Lorenzo Richelmy',
  'marcella': 'Anna Friel',
  'masters-of-sex': 'Michael Sheen',
  'masters-of-the-air': 'Austin Butler',
  'masters-of-the-universe-revelation': 'Mark Hamill',
  'mayor-of-kingstown': 'Jeremy Renner',
  'medium': 'Patricia Arquette',
  'merlin': 'Colin Morgan',
  'miami-vice': 'Don Johnson',
  'mike-molly': 'Billy Gardell',
  'midsomer-murders': 'John Nettles',
  'the-midnight-club': 'Iman Benson',
  'the-mindy-project': 'Mindy Kaling',
  'missing': 'James Nesbitt',
  'the-missing': 'James Nesbitt',
  'mob-psycho-100': 'Setsuo Ito',
  'mobland': 'Tom Hardy',
  'modern-love': 'Anne Hathaway',
  'monarch-legacy-of-monsters': 'Kurt Russell',
  'moonlighting': 'Cybill Shepherd',
  'mr-mercedes': 'Brendan Gleeson',
  'murderbot': 'Alexander Skarsgård',
  'murder-she-wrote': 'Angela Lansbury',
  'mythbusters': 'Adam Savage',
  'mythic-quest': 'Rob McElhenney',
  'my-wife-and-kids': 'Damon Wayans',
  // ── N ──
  'nashville': 'Connie Britton',
  'nathan-for-you': 'Nathan Fielder',
  'ncis-los-angeles': 'Chris O\'Donnell',
  'never-have-i-ever': 'Maitreyi Ramakrishnan',
  'neon-genesis-evangelion': 'Spike Spencer',
  'nikita': 'Maggie Q',
  'nip-tuck': 'Dylan Walsh',
  'nobody-wants-this': 'Kristen Bell',
  'numb3rs': 'Rob Morrow',
  // ── O ──
  'one-tree-hill': 'Chad Michael Murray',
  'only-fools-and-horses': 'David Jason',
  'our-flag-means-death': 'Taika Waititi',
  'our-planet': 'David Attenborough',
  // ── P ──
  'painkiller': 'Uzo Aduba',
  'parenthood': 'Lauren Graham',
  'party-down': 'Adam Scott',
  'patrick-melrose': 'Benedict Cumberbatch',
  'pam-tommy': 'Lily James',
  'pieces-of-her': 'Toni Collette',
  'phineas-and-ferb': 'Vincent Martella',
  'pinky-and-the-brain': 'Rob Paulsen',
  'poirot': 'David Suchet',
  'poker-face': 'Natasha Lyonne',
  'pose': 'Billy Porter',
  'presumed-innocent': 'Jake Gyllenhaal',
  'pride-and-prejudice': 'Colin Firth',
  'private-practice': 'Kate Walsh',
  'pushing-daisies': 'Lee Pace',
  // ── Q ──
  'qi': 'Stephen Fry',
  'quantum-leap': 'Scott Bakula',
  'queen-charlotte-a-bridgerton-story': 'India Amarteifio',
  'queen-of-the-south': 'Alice Braga',
  'quantico': 'Priyanka Chopra',
  // ── R ──
  'raised-by-wolves': 'Amanda Collin',
  'raising-hope': 'Lucas Neff',
  'ratched': 'Sarah Paulson',
  'ray-donovan': 'Liev Schreiber',
  'recess': 'Andrew Lawrence',
  'rectify': 'Aden Young',
  'red-dwarf': 'Craig Charles',
  'regular-show': 'J.G. Quintel',
  'reign': 'Adelaide Kane',
  'resident-alien': 'Alan Tudyk',
  'rescue-me': 'Denis Leary',
  'revolution': 'Billy Burke',
  'ripley': 'Andrew Scott',
  'rizzoli-isles': 'Angie Harmon',
  'river': 'Stellan Skarsgård',
  'rogue-heroes': 'Jack O\'Connell',
  'robot-chicken': 'Seth Green',
  'roseanne': 'Roseanne Barr',
  'roswell': 'Shiri Appleby',
  'runaways': 'Rhenzy Feliz',
  'rugrats': 'E.G. Daily',
  'rules-of-engagement': 'David Spade',
  // ── S ──
  'sabrina-the-teenage-witch': 'Melissa Joan Hart',
  'samurai-champloo': 'Kazuya Nakai',
  'samurai-jack': 'Phil LaMarr',
  'santa-clarita-diet': 'Drew Barrymore',
  'saturday-night-live': 'Lorne Michaels',
  'saved-by-the-bell': 'Mark-Paul Gosselaar',
  'scavengers-reign': 'Bob Stephenson',
  'scandal': 'Kerry Washington',
  'scorpion': 'Elyes Gabel',
  'scream-queens': 'Emma Roberts',
  'scream-the-tv-series': 'Willa Fitzgerald',
  'scooby-doo-where-are-you': 'Don Messick',
  'seal-team': 'David Boreanaz',
  'secret-invasion': 'Samuel L. Jackson',
  'secret-level': 'Arnold Schwarzenegger',
  'series-of-unfortunate-events': 'Neil Patrick Harris',
  'a-series-of-unfortunate-events': 'Neil Patrick Harris',
  'the-sex-lives-of-college-girls': 'Pauline Chalamet',
  'sex-life': 'Sarah Shahi',
  'shadowhunters': 'Katherine McNamara',
  'the-shannara-chronicles': 'Austin Butler',
  'shetland': 'Douglas Henshall',
  'shooter': 'Ryan Phillippe',
  'skeleton-crew': 'Jude Law',
  'sleepy-hollow': 'Tom Mison',
  'sneaky-pete': 'Giovanni Ribisi',
  'snowfall': 'Damson Idris',
  'snowpiercer': 'Jennifer Connelly',
  'solar-opposites': 'Justin Roiland',
  'solo-leveling': 'Taito Ban',
  'southland': 'Michael Cudlitz',
  'space-force': 'Steve Carell',
  'spaced': 'Simon Pegg',
  'spider-man-the-animated-series': 'Christopher Daniel Barnes',
  'spy-x-family': 'Takuya Eguchi',
  'startup': 'Adam Brody',
  'star-trek': 'William Shatner',
  'star-trek-deep-space-nine': 'Avery Brooks',
  'star-trek-enterprise': 'Scott Bakula',
  'star-trek-lower-decks': 'Tawny Newsome',
  'star-trek-picard': 'Patrick Stewart',
  'star-trek-strange-new-worlds': 'Anson Mount',
  'star-trek-voyager': 'Kate Mulgrew',
  'star-wars-clone-wars': 'Mat Lucas',
  'star-wars-rebels': 'Taylor Gray',
  'star-wars-the-bad-batch': 'Dee Bradley Baker',
  'star-wars-tales-of-the-jedi': 'Ashley Eckstein',
  'stay-close': 'Cush Jumbo',
  'steven-universe': 'Zach Callison',
  'strike-back': 'Philip Winchester',
  'studio-60-on-the-sunset-strip': 'Matthew Perry',
  'suburgatory': 'Jane Levy',
  'sugar': 'Colin Farrell',
  'the-suit-life-of-zack-cody': 'Dylan Sprouse',
  'the-suite-life-of-zack-cody': 'Dylan Sprouse',
  'superman-lois': 'Tyler Hoechlin',
  'superstore': 'America Ferrera',
  'survivor': 'Jeff Probst',
  'sweet-tooth': 'Christian Convery',
  // ── T ──
  'taskmaster': 'Greg Davies',
  'the-a-team': 'George Peppard',
  'the-affair': 'Dominic West',
  'teen-titans': 'Scott Menville',
  'teen-titans-go': 'Scott Menville',
  'terra-nova': 'Jason O\'Mara',
  'that-90s-show': 'Callie Haverda',
  'the-4400': 'Joel Gretsch',
  'the-amazing-world-of-gumball': 'Logan Grove',
  'the-black-list': 'James Spader',
  'the-borgias': 'Jeremy Irons',
  'the-boondocks': 'Regina King',
  'the-capture': 'Holliday Grainger',
  'the-carrie-diaries': 'AnnaSophia Robb',
  'the-cleveland-show': 'Mike Henry',
  'the-closer': 'Kyra Sedgwick',
  'the-cosby-show': 'Bill Cosby',
  'the-crowded-room': 'Tom Holland',
  'the-dark-crystal-age-of-resistance': 'Taron Egerton',
  'the-deuce': 'James Franco',
  'the-devil-s-hour': 'Peter Capaldi',
  'the-dragon-prince': 'Jack De Sena',
  'the-dropout': 'Amanda Seyfried',
  'the-english': 'Emily Blunt',
  'the-exorcist': 'Geena Davis',
  'the-fairly-oddparents': 'Tara Strong',
  'the-flight-attendant': 'Kaley Cuoco',
  'the-fosters': 'Teri Polo',
  'the-four-seasons': 'Steve Carell',
  'the-gifted': 'Stephen Moyer',
  'the-gilded-age': 'Christine Baranski',
  'the-golden-girls': 'Bea Arthur',
  'the-grand-tour': 'Jeremy Clarkson',
  'the-great': 'Elle Fanning',
  'the-jinx-the-life-and-deaths-of-robert-durst': 'Robert Durst',
  'the-knick': 'Clive Owen',
  'the-kominsky-method': 'Michael Douglas',
  'the-l-word': 'Jennifer Beals',
  'the-last-man-on-earth': 'Will Forte',
  'the-league': 'Mark Duplass',
  'the-legend-of-vox-machina': 'Travis Willingham',
  'the-lincoln-lawyer': 'Manuel Garcia-Rulfo',
  'the-magicians': 'Jason Ralph',
  'the-middle': 'Patricia Heaton',
  'the-midnight-gospel': 'Duncan Trussell',
  'the-mist': 'Morgan Spector',
  'the-nanny': 'Fran Drescher',
  'the-nevers': 'Laura Donnelly',
  'the-o-c': 'Ben McKenzie',
  'the-offer': 'Miles Teller',
  'the-order': 'Jake Manley',
  'the-patient': 'Steve Carell',
  'the-peripheral': 'Chloë Grace Moretz',
  'the-pillars-of-the-earth': 'Eddie Redmayne',
  'the-powerpuff-girls': 'Cathy Cavadini',
  'the-recruit': 'Noah Centineo',
  'the-rehearsal': 'Nathan Fielder',
  'the-residence': 'Uzo Aduba',
  'the-resident': 'Matt Czuchry',
  'the-righteous-gemstones': 'Danny McBride',
  'the-secret-circle': 'Britt Robertson',
  'the-society': 'Kathryn Newton',
  'the-spy': 'Sacha Baron Cohen',
  'the-staircase': 'Colin Firth',
  'the-stand': 'James Marsden',
  'the-strain': 'Corey Stoll',
  'the-studio': 'Seth Rogen',
  'the-summer-i-turned-pretty': 'Lola Tung',
  'the-thick-of-it': 'Peter Capaldi',
  'the-tomorrow-people': 'Robbie Amell',
  'the-tourist': 'Jamie Dornan',
  'the-tudors': 'Jonathan Rhys Meyers',
  'the-venture-bros': 'James Urbaniak',
  'the-vietnam-war': 'Peter Coyote',
  'the-wonder-years': 'Fred Savage',
  'the-world-at-war': 'Laurence Olivier',
  'tiger-king': 'Joe Exotic',
  'timeless': 'Abigail Spencer',
  'tokyo-ghoul': 'Austin Tindle',
  'tokyo-vice': 'Ansel Elgort',
  'torchwood': 'John Barrowman',
  'touch': 'Kiefer Sutherland',
  'top-boy': 'Ashley Walters',
  'top-of-the-lake': 'Elisabeth Moss',
  'trailer-park-boys': 'Mike Smith',
  'travelers': 'Eric McCormack',
  'twisted-metal': 'Anthony Mackie',
  // ── U ──
  'ugly-betty': 'America Ferrera',
  'unbreakable-kimmy-schmidt': 'Ellie Kemper',
  'upload': 'Robbie Amell',
  'utopia': 'Olivia Colman',
  // ── V ──
  'v': 'Elizabeth Mitchell',
  'velma': 'Mindy Kaling',
  'venture-bros': 'James Urbaniak',
  'veronica-mars': 'Kristen Bell',
  'vice-principals': 'Danny McBride',
  'victoria': 'Jenna Coleman',
  'vigil': 'Suranne Jones',
  'vikings-valhalla': 'Sam Corlett',
  'villains': 'Bill Skarsgård',
  'virgin-river': 'Alexandra Breckenridge',
  // ── W ──
  'warehouse-13': 'Eddie McClintock',
  'warrior': 'Andrew Koji',
  'warrior-nun': 'Alba Baptista',
  'wayward-pines': 'Matt Dillon',
  'we-own-this-city': 'Jon Bernthal',
  'west-wing': 'Martin Sheen',
  'the-west-wing': 'Martin Sheen',
  'wild-wild-country': 'Chapman Way',
  'wilfred': 'Elijah Wood',
  'will-grace': 'Eric McCormack',
  'willow': 'Warwick Davis',
  'winning-time-the-rise-of-the-lakers-dynasty': 'John C. Reilly',
  'wizards-of-waverly-place': 'Selena Gomez',
  'workaholics': 'Blake Anderson',
  // ── X Y Z ──
  'x-men': 'Cedric Smith',
  'x-men-97': 'Ray Chase',
  'xena-warrior-princess': 'Lucy Lawless',
  'years-and-years': 'Emma Thompson',
  'you-re-the-worst': 'Aya Cash',
  'young-justice': 'Danica McKellar',
  'young-rock': 'Adrian Groulx',
  'your-friends-neighbors': 'Jon Hamm',
  'your-honor': 'Bryan Cranston',
  'z-nation': 'Harold Perrineau',
  'zero-day': 'Robert De Niro',
  // ── Additional entries missing from initial pass ──
  '1923': 'Harrison Ford',
  '12-monkeys': 'Aaron Stanford',
  '24-live-another-day': 'Kiefer Sutherland',
  '3rd-rock-from-the-sun': 'John Lithgow',
  '90210': 'Shenae Grimes',
  '9-1-1': 'Angela Bassett',
  'a-discovery-of-witches': 'Teresa Palmer',
  'a-man-on-the-inside': 'Ted Danson',
  'a-murder-at-the-end-of-the-world': 'Emma Corrin',
  'according-to-jim': 'Jim Belushi',
  'alien-earth': 'Sydney Chandler',
  'almost-human': 'Karl Urban',
  'an-idiot-abroad': 'Karl Pilkington',
  'archive-81': 'Mamoudou Athie',
  'berserk': 'Marc Diraison',
  'blackadder': 'Rowan Atkinson',
  'blackadder-goes-forth': 'Rowan Atkinson',
  'blackadder-ii': 'Rowan Atkinson',
  'blackadder-the-third': 'Rowan Atkinson',
  'bleach': 'Johnny Yong Bosch',
  'bleach-thousand-year-blood-war': 'Johnny Yong Bosch',
  'blue-planet-ii': 'David Attenborough',
  'c-b-strike': 'Tom Burke',
  'castlevania': 'Richard Armitage',
  'clarkson-s-farm': 'Jeremy Clarkson',
  'coupling': 'Jack Davenport',
  'death-in-paradise': 'Ben Miller',
  'dragon-ball': 'Stephanie Nadolny',
  'dragon-ball-super': 'Masako Nozawa',
  'episodes': 'Matt LeBlanc',
  'evil': 'Katja Herbers',
  'family-matters': 'Jaleel White',
  'frasier': 'Kelsey Grammer',
  'frieren-beyond-journey-s-end': 'Atsumi Tanezaki',
  'full-house': 'Bob Saget',
  'gangs-of-london': 'Sope Dirisu',
  'griselda': 'Sofía Vergara',
  'happy': 'Christopher Meloni',
  'happy-endings': 'Eliza Coupe',
  'heroes-reborn': 'Jack Coleman',
  'hollywood': 'Darren Criss',
  'how-i-met-your-father': 'Hilary Duff',
  'human-planet': 'John Hurt',
  'i-am-groot': 'Vin Diesel',
  'impractical-jokers': 'Joe Gatto',
  'inhumans': 'Anson Mount',
  'jury-duty-presents-company-retreat': 'Mekki Leeper',
  'keeping-up-with-the-kardashians': 'Kim Kardashian',
  'lessons-in-chemistry': 'Brie Larson',
  'letterkenny': 'Jared Keeso',
  'm-a-s-h': 'Alan Alda',
  'man-vs-bee': 'Rowan Atkinson',
  'master-of-none': 'Aziz Ansari',
  'messiah': 'Mehdi Dehbi',
  'mom': 'Anna Faris',
  'monty-python-s-flying-circus': 'John Cleese',
  'mr-inbetween': 'Scott Ryan',
  'mr-mrs-smith': 'Donald Glover',
  'one-day': 'Ambika Mod',
  'over-the-garden-wall': 'Elijah Wood',
  'paradise': 'Sterling K. Brown',
  'parasyte-the-maxim': 'Nobunaga Shimazaki',
  'peep-show': 'David Mitchell',
  'percy-jackson-and-the-olympians': 'Walker Scobell',
  'pok-mon': 'Veronica Taylor',
  'poldark': 'Aidan Turner',
  'preacher': 'Dominic Cooper',
  'resident-evil': 'Ella Balinska',
  's-w-a-t': 'Shemar Moore',
  'safe': 'Michael C. Hall',
  'scenes-from-a-marriage': 'Oscar Isaac',
  'servant': 'Lauren Ambrose',
  'sirens': 'Kevin Daniels',
  'stargate-atlantis': 'Joe Flanigan',
  'stargate-universe': 'Robert Carlyle',
  'steins-gate': 'Mamoru Miyano',
  'swamp-thing': 'Derek Mears',
  'sword-art-online': 'Yoshitsugu Matsuoka',
  'tales-from-the-crypt': 'John Kassir',
  'ted': 'Max Burkholder',
  'teenage-mutant-ninja-turtles': 'Rob Paulsen',
  'the-alienist': 'Daniel Brühl',
  'the-blue-planet': 'David Attenborough',
  'the-chosen': 'Jonathan Roumie',
  'the-daily-show': 'Jon Stewart',
  'the-filthy-frank-show': 'Joji',
  'the-goldbergs': 'Wendi McLendon-Covey',
  'the-inbetweeners': 'Simon Bird',
  'the-king-of-queens': 'Kevin James',
  'the-perfect-couple': 'Nicole Kidman',
  'the-promised-neverland': 'Sumire Morohoshi',
  'the-ranch': 'Ashton Kutcher',
  'the-serpent': 'Tahar Rahim',
  'the-stranger': 'Richard Armitage',
  'the-walking-dead-daryl-dixon': 'Norman Reedus',
  'the-walking-dead-dead-city': 'Lauren Cohan',
  'the-walking-dead-the-ones-who-live': 'Andrew Lincoln',
  'the-white-queen': 'Rebecca Ferguson',
  'the-woman-in-the-house-across-the-street-from-the-girl-in-the-window': 'Kristen Bell',
  'the-young-pope': 'Jude Law',
  'them': 'Deborah Ayorinde',
  'time': 'Sean Bean',
  'victorious': 'Victoria Justice',
  'war-peace': 'Paul Dano',
  'why-women-kill': 'Lucy Liu',
  'whose-line-is-it-anyway': 'Drew Carey',
  'younger': 'Sutton Foster',
};

// ── Tagline Map ────────────────────────────────────────────────────────────────
const TAG = {
  // ── A ──
  'abbott-elementary': 'Educating the future, one disaster at a time.',
  'agatha-all-along': 'The road is dangerous, darling.',
  'agent-carter': 'Saving the world on her own terms.',
  'alcatraz': 'They never escaped. They came back.',
  'alias': 'The spy who had everything — except the truth.',
  'alias-grace': 'She remembered everything. Or did she?',
  'alf': 'He\'s not your average couch potato.',
  'ally-mcbeal': 'Love, law, and a lot of dancing babies.',
  'alphas': 'They\'re extraordinary. And they\'re in your backyard.',
  'american-dad': 'Family. Country. Absolutely no sanity.',
  'american-gods': 'The old gods are angry. The new gods are afraid.',
  'american-horror-stories': 'Fear lives in the details.',
  'american-primeval': 'The West was won in blood.',
  'american-vandal': 'Who drew the dicks?',
  'anatomy-of-a-scandal': 'Power hides the dirtiest secrets.',
  'and-just-like-that': 'The next chapter begins.',
  'angels-in-america': 'The world only spins forward.',
  'anger-management': 'Some men need a little push. Charlie needs a lot.',
  'animal-kingdom': 'Family is the most dangerous gang of all.',
  'anne-with-an-e': 'An orphan who refused to stop dreaming.',
  'another-life': 'First contact changed everything.',
  'aqua-teen-hunger-force': 'They\'re food. They have no idea what they\'re doing.',
  'ash-vs-evil-dead': 'Hail to the king, baby.',
  'atypical': 'Normal is overrated.',
  'awkward': 'She survived the worst day of her life. Just barely.',
  // ── B ──
  'babylon-5': 'The last best hope for peace.',
  'bad-monkey': 'Paradise has a dark side.',
  'ballers': 'The game never stops.',
  'batman': 'The Caped Crusader battles crime in Gotham.',
  'batman-beyond': 'The future of the Dark Knight.',
  'batwoman': 'A new hero guards Gotham City.',
  'baywatch': 'Sun, sand, and saving lives.',
  'beauty-and-the-beast': 'Love knows no boundaries.',
  'beavis-and-butt-head': 'This is the greatest show, huh huh.',
  'behind-her-eyes': 'Everyone is lying. Trust no one.',
  'ben-10': 'A watch that changes everything.',
  'beverly-hills-90210': 'Where zip codes define destinies.',
  'big-mouth': 'Growing up is the ultimate horror show.',
  'black-books': 'The world\'s worst bookshop. The world\'s best sitcom.',
  'black-doves': 'A spy. A hitman. A deadly secret.',
  'black-lightning': 'A father. A hero. A legend.',
  'black-rabbit': 'In the shadows, every deal has a price.',
  'black-summer': 'Survival is not a plan.',
  'bleach': 'Death is just the beginning.',
  'bleach-thousand-year-blood-war': 'The final war begins.',
  'blindspot': 'Her tattoos are the map. He\'s trying to read them.',
  'blue-bloods': 'A family sworn to serve and protect.',
  'blue-eye-samurai': 'Half-blood. Full vengeance.',
  'blue-mountain-state': 'The playbook is optional.',
  'bluey': 'Adventure is everywhere you look.',
  'bob-s-burgers': 'Burgers made with love. And a lot of chaos.',
  'bodies': 'One corpse. Four timelines. No answers.',
  'bored-to-death': 'Amateur detective. Amateur everything.',
  'boston-legal': 'The most outrageous lawyers in America.',
  'boy-meets-world': 'Life is tough. Get a helmet.',
  'broad-city': 'New York City through the eyes of best friends.',
  // ── C ──
  'call-the-midwife': 'Life. Love. Birth. In the heart of East London.',
  'carniv-le': 'Good and evil collide under the big top.',
  'carnival-row': 'The city is on the edge. So are they.',
  'castle-rock': 'All monsters are human.',
  'catdog': 'One body. Two pets. Zero sense.',
  'chainsaw-man': 'To live is to fight.',
  'chappelle-s-show': 'Comedy that told the truth.',
  'charmed': 'The power of three will set us free.',
  'cheers': 'Where everybody knows your name.',
  'chicago-fire': 'Every call could be their last.',
  'chicago-med': 'Every heartbeat counts.',
  'chicago-p-d': 'Justice lives on the streets.',
  'chucky': 'Good guys can be deadly.',
  'citadel': 'The world\'s most powerful spy agency is gone.',
  'clickbait': 'Going viral comes at a cost.',
  'cold-case': 'No victim is forgotten.',
  'code-geass': 'A prince exiled. A world changed.',
  'colony': 'Resist. Survive. At any cost.',
  'columbo': 'Just one more thing.',
  'constantine': 'Hell\'s reluctant hero.',
  'continuum': 'She traveled back to stop a future war.',
  'cosmos': 'We are made of star stuff.',
  'counterpart': 'Two worlds. One man. Infinite danger.',
  'courage-the-cowardly-dog': 'Return the slab.',
  'cougar-town': 'It\'s complicated. It\'s hilarious. It\'s Cougar Town.',
  'covert-affairs': 'Spy school never prepared her for this.',
  'crashing': 'When your life falls apart, the comedy begins.',
  'cross': 'A detective haunted by his own gifts.',
  'csi-miami': 'The truth is in the evidence.',
  'csi-ny': 'New York never sleeps. Neither do we.',
  'cunk-on-earth': 'The most profound questions ever asked, badly.',
  'cursed': 'The sword chose her.',
  // ── D ──
  'da-vinci-s-demons': 'Genius, pleasure, danger.',
  'daisy-jones-the-six': 'Some bands are lightning in a bottle.',
  'dandadan': 'Aliens exist. So do ghosts. Now what?',
  'daredevil-born-again': 'Hell\'s Kitchen needs its devil.',
  'dark-angel': 'She was engineered to be the perfect soldier.',
  'dark-matter': 'Which version of yourself would you choose?',
  'dark-winds': 'Ancient land. Modern crime.',
  'daria': 'She\'s got a lot of brains. Not a lot of friends.',
  'dawson-s-creek': 'Growing up is the hardest role you\'ll ever play.',
  'dead-like-me': 'Death is only the beginning.',
  'defiance': 'A new world built on the ruins of the old.',
  'defending-jacob': 'A father\'s love. A prosecutor\'s burden.',
  'derek': 'Kindness is magic.',
  'derry-girls': 'Growing up Catholic in 1990s Northern Ireland.',
  'devs': 'Free will is an illusion. Or is it?',
  'dexter-s-laboratory': 'The boy genius no one suspects.',
  'dexter-original-sin': 'Before the monster, there was the beginning.',
  'dharma-greg': 'Opposites don\'t just attract. They get married.',
  'dirk-gently-s-holistic-detective-agency': 'Everything is connected.',
  'disenchantment': 'A princess who refuses to be proper.',
  'dollhouse': 'They can be anyone. They remember nothing.',
  'don-t-trust-the-b-in-apartment-23': 'The worst roommate in New York City.',
  'doom-patrol': 'The world\'s strangest heroes.',
  'dracula': 'The ancient evil wakes again.',
  'drake-josh': 'Brothers by fate. Best friends by choice.',
  'ducktales': 'Adventure is just around the corner.',
  'dune-prophecy': 'Before Paul. Before the prophecy. There was the Sisterhood.',
  // ── E ──
  'eastbound-down': 'His arm is a cannon. His life is a mess.',
  'echo': 'She\'s fought her whole life to be free.',
  'ed-edd-n-eddy': 'Three kids. One scam. Zero success.',
  'endeavour': 'Before Morse, there was Endeavour.',
  'er': 'Life and death, shift after shift.',
  'eric': 'A puppeteer\'s son vanishes into New York\'s dark heart.',
  'erased': 'He can rewind time, but not his guilt.',
  'escape-at-dannemora': 'The most audacious prison break you never heard about.',
  'eureka': 'The smartest small town in America.',
  'everybody-hates-chris': 'Surviving school was harder than surviving Brooklyn.',
  'everybody-loves-raymond': 'Everybody loves him. His wife is undecided.',
  // ── F ──
  'f-is-for-family': 'The world was tougher then. So were the families.',
  'falling-skies': 'Six months after the invasion, the fight for survival begins.',
  'farscape': 'Lost in the universe. Found in adventure.',
  'father-ted': 'Three priests. One island. Absolute chaos.',
  'fate-the-winx-saga': 'Magic has consequences.',
  'feud': 'Hollywood\'s most legendary rivalry.',
  'final-space': 'A man. A planet-destroying alien. A road trip.',
  'firefly-lane': 'Friends for life. No matter the cost.',
  'first-kill': 'A vampire and a monster hunter fall for each other.',
  'flashforward': 'Everyone saw exactly two minutes of their future.',
  'flight-of-the-conchords': 'New Zealand\'s fourth most popular folk duo.',
  'the-flintstones': 'A modern Stone Age family.',
  'fool-me-once': 'She watched her dead husband on a nanny cam.',
  'forever': 'What would you do with eternity and a fresh start?',
  'formula-1-drive-to-survive': 'Behind the wheel, everything is on the line.',
  'foster-s-home-for-imaginary-friends': 'For imaginary friends without a home.',
  'fresh-off-the-boat': 'An immigrant family making America their own.',
  'friday-night-lights': 'Clear eyes. Full hearts. Can\'t lose.',
  'frozen-planet': 'Life at the extremes of our planet.',
  'fubar': 'Retired spy. Undead career.',
  'fuller-house': 'The Tanners are back. Thank God.',
  'fullmetal-alchemist': 'Two brothers. One goal. Countless sacrifices.',
  'future-man': 'A janitor is recruited to save the world.',
  // ── G ──
  'generation-kill': 'The first major battle of the Iraq War, as it was lived.',
  'ghost-whisperer': 'She sees the dead. She\'s trying to help them go.',
  'ghosts': 'A bed and breakfast with a rather ghostly staff.',
  'ginny-georgia': 'Two daughters of the same woman. Very different worlds.',
  'girls': 'The voice of a generation. Maybe.',
  'glow': 'Gorgeous Ladies of Wrestling. Unglamorous truth.',
  'godless': 'A man on the run. A woman protecting her town.',
  'goliath': 'A washed-up lawyer takes on the case of his life.',
  'good-girls': 'Three women, one bad decision, zero regrets.',
  'grace-and-frankie': 'Their husbands fell in love with each other. Now what?',
  'guillermo-del-toro-s-cabinet-of-curiosities': 'The dark imagination unleashed.',
  // ── H ──
  'haikyu': 'The shortest player wants to be the best.',
  'halt-and-catch-fire': 'Racing to build the future, destroying themselves in the process.',
  'hanna': 'She was created to be the ultimate weapon.',
  'hannah-montana': 'By day, ordinary girl. By night, rock star.',
  'harley-quinn': 'She\'s on her own now. Gotham should be scared.',
  'hart-of-dixie': 'A New York doctor trades Manhattan for Alabama.',
  'haven': 'The afflicted came to Haven for peace. They found something else.',
  'hawaii-five-0': 'An elite task force protecting paradise.',
  'hazbin-hotel': 'Can demons be rehabilitated? Probably not.',
  'heartstopper': 'Small acts of kindness. Big changes of heart.',
  'helix': 'A deadly outbreak in the Arctic. A race against extinction.',
  'hell-on-wheels': 'Building the Transcontinental Railroad in blood and iron.',
  'hemlock-grove': 'A small town harbors secrets no one wants to find.',
  'hercules-the-legendary-journeys': 'A hero walks among mortals.',
  'hey-arnold': 'A kid with a football head and a big heart.',
  'high-potential': 'She reads people. Especially the guilty ones.',
  'hijack': 'Seven hours. One hijacking. One chance.',
  'his-dark-materials': 'There are many worlds. And something hunts them all.',
  'home-improvement': 'More power! Less common sense.',
  'homecoming': 'A caseworker helps soldiers transition. Or so she thinks.',
  'hunters': 'Ex-Nazis are hiding in plain sight. Not for long.',
  // ── I ──
  'i-am-not-okay-with-this': 'She\'s angry. She has no idea what she\'s capable of.',
  'i-love-lucy': 'The funniest woman in television history.',
  'icarly': 'Teens, cameras, and a whole lot of trouble.',
  'inside-job': 'Welcome to the deep state. It\'s a mess.',
  'insatiable': 'She was bullied. Now she fights back with a crown.',
  'interview-with-the-vampire': 'An immortal life means endless tragedy.',
  'into-the-badlands': 'A warrior and a boy navigate a dangerous feudal state.',
  'invasion': 'The end of the world looks different from every angle.',
  'inventing-anna': 'She conned New York\'s elite. Was she a genius or a fraud?',
  'ironheart': 'She built something the world wasn\'t ready for.',
  'it-s-a-sin': 'Young. Brilliant. Dying too soon.',
  'it-welcome-to-derry': 'Derry\'s children disappear. Something lurks below.',
  'izombie': 'She\'s undead, works at a morgue, and eats brains.',
  // ── J ──
  'jackass': 'Stupidity has never been this entertaining.',
  'jane-the-virgin': 'Virginal. Accidental. Pregnant.',
  'jericho': 'A nuclear attack. A small Kansas town fights to survive.',
  'joey': 'How you doin\'? Not great, actually.',
  'johnny-bravo': 'Pretty. Dumb. Irresistibly Irresistible.',
  'jojo-s-bizarre-adventure': 'The Joestars face evil across generations.',
  'jupiter-s-legacy': 'The first generation of superheroes is aging. Their children are not ready.',
  'justice-league': 'The world\'s greatest heroes, united.',
  // ── K ──
  'kaos': 'The Greek gods are falling apart.',
  'kaleidoscope': 'Eight episodes. Eight angles. One heist.',
  'key-and-peele': 'Comedy that held up a mirror to America.',
  'kim-possible': 'She can do anything. Really.',
  'king-of-the-hill': 'Propane and propane accessories.',
  'knight-rider': 'One man can make a difference.',
  'kyle-xy': 'He was born without a belly button. That\'s just the beginning.',
  // ── L ──
  'landman': 'Oil, power, and a price for everything.',
  'las-vegas': 'What happens in Vegas... is usually illegal.',
  'last-man-standing': 'He\'s surrounded by women. He\'s winning.',
  'last-week-tonight-with-john-oliver': 'Breaking news. Without the breaking.',
  'the-last-man-on-earth': 'Phil Miller is the last man on earth. Lucky him.',
  'the-last-ship': 'A destroyer crew fights to save mankind from a deadly plague.',
  'law-order': 'Ripped from the headlines.',
  'law-order-criminal-intent': 'Inside the criminal mind.',
  'legend-of-the-seeker': 'The sword has chosen its keeper.',
  'legacies': 'The next generation of supernatural.',
  'legion': 'The most powerful mutant may also be the most dangerous.',
  'lethal-weapon': 'One rule: no rules.',
  'life': 'He was convicted of murder. Now he\'s back on the force.',
  'life-on-mars': 'Detective Sam Tyler is shot, and wakes up in 1973.',
  'limitless': 'NZT-48 shows you what you\'re capable of.',
  'line-of-duty': 'It\'s not about bent coppers. It\'s about what makes them.',
  'lioness': 'She trains America\'s deadliest female operatives.',
  'little-fires-everywhere': 'Little secrets. Big consequences.',
  'little-house-on-the-prairie': 'A family finding their way on the American frontier.',
  'living-with-yourself': 'He paid for a new him. He got something worse.',
  'lockwood-co': 'Ghost hunting is the new career path.',
  'locke-key': 'Magic keys unlock a family\'s darkest secrets.',
  'longmire': 'A sheriff who keeps his own counsel, and his own justice.',
  'lost-girl': 'She\'s a succubus navigating the world of the Fae.',
  'louie': 'The most uncomfortable comedy on television.',
  'lovecraft-country': 'America has always been a horror story.',
  'love': 'What does love really look like?',
  'love-death': 'Did she do it? And did she have a reason?',
  // ── M ──
  'macgyver': 'A paper clip and duct tape can save the world.',
  'mad-about-you': 'Marriage is complicated. They love it anyway.',
  'magnum-p-i': 'A veteran takes on dangerous cases in Hawaii.',
  'maniac': 'A pill promises to fix all your problems. It doesn\'t.',
  'manhunt': 'The world\'s most famous fugitive hunt.',
  'manifest': 'Flight 828 disappeared. Five years later, it landed.',
  'marco-polo': 'The merchant\'s son who changed the world.',
  'marcella': 'A detective returned to work just in time for a murder.',
  'masters-of-sex': 'The untold story of sexuality\'s scientific pioneers.',
  'masters-of-the-air': 'They flew into hell so the world could be free.',
  'masters-of-the-universe-revelation': 'He-Man\'s most dangerous chapter begins.',
  'mayor-of-kingstown': 'Power and punishment in a town that runs on prisons.',
  'medium': 'She talks to the dead. The living pay attention.',
  'merlin': 'A young warlock and a future king forge a legend.',
  'miami-vice': 'Style. Danger. South Florida in neon.',
  'mike-molly': 'They met at Overeaters Anonymous. They found something better.',
  'midsomer-murders': 'A charming English county with a suspicious murder rate.',
  'the-midnight-club': 'Eight teenagers with terminal diagnoses. One pact.',
  'the-mindy-project': 'She\'s a doctor obsessed with romantic comedies.',
  'the-missing': 'A father never stops searching for his son.',
  'mob-psycho-100': 'A boy with immeasurable psychic power just wants to be normal.',
  'mobland': 'London\'s criminal empire doesn\'t give second chances.',
  'modern-love': 'Love in all its forms, complications, and revelations.',
  'monarch-legacy-of-monsters': 'The Titan world has kept its secrets long enough.',
  'moonlighting': 'Maddie and David solve cases. And argue. A lot.',
  'mr-mercedes': 'He killed eight people with a car. The detective never forgot.',
  'murderbot': 'A rogue security bot who just wants to watch TV.',
  'murder-she-wrote': 'Trouble follows wherever she writes.',
  'mythbusters': 'Myths, mayhem, and magnificent explosions.',
  'mythic-quest': 'Making the world\'s greatest video game is a battlefield.',
  'my-wife-and-kids': 'A father\'s unconventional parenting techniques.',
  // ── N ──
  'nashville': 'The music capital of the world. The drama capital, too.',
  'nathan-for-you': 'He\'s here to help small businesses. They\'re in trouble.',
  'ncis-los-angeles': 'The most dangerous cases start here.',
  'neon-genesis-evangelion': 'Giant robots, angels, and the weight of saving humanity.',
  'never-have-i-ever': 'Grief, boys, and the chaos of teenage life.',
  'nikita': 'She was trained to kill. Now she\'s fighting back.',
  'nip-tuck': 'Beneath the beautiful skin lies something ugly.',
  'nobody-wants-this': 'An agnostic podcast host meets a rabbi. It gets complicated.',
  'numb3rs': 'He uses math to catch criminals.',
  // ── O ──
  'one-tree-hill': 'Two brothers. One ball. A lifetime of rivalry.',
  'only-fools-and-horses': 'He who dares, wins. Sometimes.',
  'our-flag-means-death': 'A gentleman pirate falls for Blackbeard.',
  'our-planet': 'The miracle of life on Earth.',
  // ── P ──
  'painkiller': 'How a family turned pain into profit.',
  'parenthood': 'The Braverman family tries its best.',
  'party-down': 'Failed actors cater Hollywood parties.',
  'patrick-melrose': 'A man spends a lifetime surviving his upbringing.',
  'pam-tommy': 'The tape that changed privacy forever.',
  'pieces-of-her': 'She never knew her mother at all.',
  'phineas-and-ferb': 'Summer lasts 104 days. Use every one.',
  'pinky-and-the-brain': 'Tonight we try to take over the world.',
  'poirot': 'The little grey cells are always at work.',
  'poker-face': 'She can always tell when someone\'s lying.',
  'pose': 'New York\'s ballroom scene, full of life and fire.',
  'presumed-innocent': 'A prosecutor accused becomes the defendant.',
  'pride-and-prejudice': 'It is a truth universally acknowledged...',
  'private-practice': 'A new start in Los Angeles. Same complicated life.',
  'pushing-daisies': 'He can bring the dead back to life with a touch.',
  // ── Q ──
  'qi': 'Quite Interesting facts from quite interesting minds.',
  'quantum-leap': 'Putting right what once went wrong.',
  'queen-charlotte-a-bridgerton-story': 'The making of a queen, and a love match.',
  'queen-of-the-south': 'She fled the cartel. Now she runs one.',
  'quantico': 'The best and brightest recruits have the darkest secrets.',
  // ── R ──
  'raised-by-wolves': 'Androids versus believers. The future hangs in balance.',
  'raising-hope': 'One night changed his life forever. Literally.',
  'ratched': 'Before the ward, there was the woman.',
  'ray-donovan': 'The fixer for the rich and powerful. At a personal cost.',
  'recess': 'The most important 20 minutes of the school day.',
  'rectify': 'A man released from death row. Justice is complicated.',
  'red-dwarf': 'Three million years in deep space. Help.',
  'regular-show': 'A groundskeeper and a raccoon have the weirdest adventures.',
  'reign': 'Mary, Queen of Scots fights for her crown.',
  'resident-alien': 'An alien hiding as a doctor in a small Colorado town.',
  'rescue-me': 'He runs into burning buildings. Life outside is harder.',
  'revolution': 'The power went out. The world fell apart.',
  'ripley': 'Tom Ripley is not who he says he is.',
  'rizzoli-isles': 'A detective and a medical examiner crack Boston\'s toughest cases.',
  'river': 'A detective haunted by visions of the dead.',
  'rogue-heroes': 'The original special forces. Raw, reckless, revolutionary.',
  'robot-chicken': 'Adult Swim\'s weirdest, most violent toy chest.',
  'roseanne': 'A working-class family that tells it like it is.',
  'roswell': 'What if aliens were hiding in a New Mexico town?',
  'runaways': 'They discovered their parents were villains. Time to run.',
  'rugrats': 'Adventure from the baby\'s perspective.',
  'rules-of-engagement': 'Four friends at very different stages of love.',
  // ── S ──
  'sabrina-the-teenage-witch': 'Half witch, half teenager, all trouble.',
  'samurai-champloo': 'A hip-hop samurai road trip through Edo Japan.',
  'samurai-jack': 'A samurai, lost in time, fighting his way home.',
  'santa-clarita-diet': 'She\'s undead. He\'s very supportive.',
  'saturday-night-live': 'Live from New York, it\'s Saturday Night!',
  'saved-by-the-bell': 'The coolest kids at Bayside High.',
  'scavengers-reign': 'Stranded on an alien world of impossible beauty and danger.',
  'scandal': 'In Washington, every secret has a price.',
  'scorpion': 'Genius has never been more dangerous.',
  'scream-queens': 'A sorority house becomes a crime scene.',
  'scream-the-tv-series': 'The killer has a new generation to terrify.',
  'scooby-doo-where-are-you': 'Would you do it for a Scooby Snack?',
  'seal-team': 'America\'s elite warriors face the world\'s worst threats.',
  'secret-invasion': 'Who can you trust when anyone could be a Skrull?',
  'secret-level': 'The greatest video games, brought to life.',
  'series-of-unfortunate-events': 'Count Olaf is always one step ahead.',
  'a-series-of-unfortunate-events': 'Count Olaf is always one step ahead.',
  'sex-life': 'Old flames have a way of burning hotter.',
  'the-sex-lives-of-college-girls': 'College: sex, secrets, and self-discovery.',
  'shadowhunters': 'Part human, part angel, total warrior.',
  'the-shannara-chronicles': 'An Elf must save the world. She didn\'t plan on this.',
  'shetland': 'A detective series set in Scotland\'s remote islands.',
  'shooter': 'A Marine sniper is framed for an assassination.',
  'skeleton-crew': 'Four kids discover a gateway to another world.',
  'sleepy-hollow': 'Ichabod Crane wakes up in modern-day Sleepy Hollow.',
  'sneaky-pete': 'A con man borrows a stranger\'s identity. Bad idea.',
  'snowfall': 'Crack cocaine hit Los Angeles. He was there at the start.',
  'snowpiercer': 'All of humanity on one train. Divided by class.',
  'solar-opposites': 'Alien roommates argue about Earth while protecting it.',
  'solo-leveling': 'The weakest hunter becomes the strongest.',
  'southland': 'Real police work. Raw, unfiltered, exhausting.',
  'space-force': 'Defending America from threats above the atmosphere.',
  'spaced': 'Two strangers fake a relationship to get the perfect flat.',
  'spider-man-the-animated-series': 'With great power, there must also come great responsibility.',
  'spy-x-family': 'Spy. Assassin. Telepath. The perfect family.',
  'startup': 'Building the future with stolen money.',
  'star-trek': 'Space: the final frontier.',
  'star-trek-deep-space-nine': 'The most complex corner of the Star Trek universe.',
  'star-trek-enterprise': 'Before the Federation, there was the beginning.',
  'star-trek-lower-decks': 'The least important ship in the fleet has the best crew.',
  'star-trek-picard': 'The legend returns to the stars.',
  'star-trek-strange-new-worlds': 'To boldly go into new adventure.',
  'star-trek-voyager': '70,000 light years from home. Alone.',
  'star-wars-clone-wars': 'The war that shaped the galaxy.',
  'star-wars-rebels': 'Hope begins with a small act of rebellion.',
  'star-wars-the-bad-batch': 'Elite clones forge their own path after Order 66.',
  'star-wars-tales-of-the-jedi': 'The Force works in mysterious ways.',
  'stay-close': 'Old lives have a way of catching up.',
  'steven-universe': 'A boy, a gem, and a galaxy to protect.',
  'strike-back': 'Black Ops. No rules. No mercy.',
  'studio-60-on-the-sunset-strip': 'Backstage at TV\'s most prestigious sketch show.',
  'suburgatory': 'A Manhattan teenager stranded in suburbia.',
  'sugar': 'A private detective with an old Hollywood obsession.',
  'the-suite-life-of-zack-cody': 'Living in a hotel never gets old.',
  'superman-lois': 'Even Superman faces his hardest battle at home.',
  'superstore': 'Big box retail. Small problems. Giant laughs.',
  'survivor': 'Outwit. Outplay. Outlast.',
  'sweet-tooth': 'Half deer, half boy, searching for home.',
  // ── T ──
  'taskmaster': 'A comedy king assigns pointless tasks. Comics comply.',
  'the-a-team': 'If you have a problem, if no one else can help...',
  'the-affair': 'An infidelity told from two perspectives.',
  'teen-titans': 'The next generation of DC heroes.',
  'teen-titans-go': 'Sidekicks in charge. Hilarity follows.',
  'terra-nova': 'Humanity\'s last chance is 85 million years in the past.',
  'that-90s-show': 'The Formans host the next generation.',
  'the-4400': 'They were abducted. Now they\'re back. All 4,400 of them.',
  'the-amazing-world-of-gumball': 'The most wonderfully weird cartoon in Elmore.',
  'the-borgias': 'The original crime family.',
  'the-boondocks': 'Two Black kids from Chicago navigate suburban Maryland.',
  'the-capture': 'Deep fakes. Government cover-ups. One detective.',
  'the-carrie-diaries': 'Before Carrie Bradshaw, there was a girl and a diary.',
  'the-cleveland-show': 'Cleveland Brown finally gets the spotlight.',
  'the-closer': 'She solves the unsolvable. Her personal life is another matter.',
  'the-cosby-show': 'An upper-class family that laughed through everything.',
  'the-crowded-room': 'The true story of the first successful multiple personality defense.',
  'the-dark-crystal-age-of-resistance': 'Three Gelflings try to save Thra.',
  'the-deuce': 'The origins of the porn industry and Times Square grit.',
  'the-devil-s-hour': 'His son wakes up every night at 3:33 a.m. screaming.',
  'the-dragon-prince': 'Elves and humans find common cause for peace.',
  'the-dropout': 'How a Stanford dropout fooled Silicon Valley.',
  'the-english': 'A woman tracks her son\'s killer across the American West.',
  'the-exorcist': 'The demon has returned. The priests are ready.',
  'the-fairly-oddparents': 'Timmy Turner wished for fairy godparents. He got two.',
  'the-flight-attendant': 'She woke up next to a dead man. She knows nothing.',
  'the-fosters': 'A non-traditional family defined by love, not biology.',
  'the-four-seasons': 'A television revival of the classic family comedy.',
  'the-gifted': 'Mutants building a future in a world that fears them.',
  'the-gilded-age': 'Old money meets new money in Gilded Age New York.',
  'the-golden-girls': 'Four women. One house. Endless cheesecake.',
  'the-grand-tour': 'Three friends, incredible cars, no censorship.',
  'the-great': 'Catherine the Great was not always so great.',
  'the-jinx-the-life-and-deaths-of-robert-durst': 'A documentary that caught a killer on camera.',
  'the-knick': 'Surgery was new, dangerous, and thrilling in 1900.',
  'the-l-word': 'Love, identity, and community in Los Angeles.',
  'the-last-man-on-earth': 'Phil thought being the last man alive would be fun.',
  'the-league': 'Fantasy football destroys friendships. Worth it.',
  'the-legend-of-vox-machina': 'Dungeons & Dragons heroes on an epic animated quest.',
  'the-lincoln-lawyer': 'He works from the back of a Lincoln. He\'s brilliant.',
  'the-magicians': 'Hogwarts for damaged adult magicians.',
  'the-middle': 'A middle-class Midwestern family just trying to survive.',
  'the-midnight-gospel': 'A podcast about the universe\'s deepest questions.',
  'the-mist': 'Something in the mist hunts survivors of a New England town.',
  'the-nanny': 'A nanny from Queens turns a British widower\'s world upside down.',
  'the-nevers': 'Victorian women develop strange powers. Society panics.',
  'the-o-c': 'A kid from the wrong side of town lands in Newport Beach.',
  'the-offer': 'The behind-the-scenes story of making The Godfather.',
  'the-order': 'A frat is actually a dark magical order.',
  'the-patient': 'A therapist is held captive by his patient.',
  'the-peripheral': 'She thought it was a game. It\'s the future.',
  'the-pillars-of-the-earth': 'Building a cathedral in medieval England.',
  'the-powerpuff-girls': 'Sugar, spice, and everything nice. Plus Chemical X.',
  'the-recruit': 'A new CIA lawyer is immediately in over his head.',
  'the-rehearsal': 'What if you could rehearse life before you live it?',
  'the-residence': 'A murder at the White House. A detective with a method.',
  'the-resident': 'Medicine as it actually is. Messy and miraculous.',
  'the-righteous-gemstones': 'A family of televangelists with zero moral authority.',
  'the-secret-circle': 'She\'s new in town. So is witchcraft.',
  'the-society': 'The adults vanished. The teens must build a new world.',
  'the-spy': 'The true story of Israel\'s greatest spy.',
  'the-staircase': 'Did he push her? Or did the owl do it?',
  'the-stand': 'A plague kills most of humanity. Good and evil divide the rest.',
  'the-strain': 'A vampire plague spreads through New York City.',
  'the-studio': 'Running a Hollywood studio is a lot like herding cats.',
  'the-summer-i-turned-pretty': 'A summer. A triangle. A choice.',
  'the-thick-of-it': 'British government, ruthlessly satirized.',
  'the-tomorrow-people': 'The next step in human evolution doesn\'t want to be found.',
  'the-tourist': 'He has no memory. Someone wants him dead.',
  'the-tudors': 'Henry VIII\'s reign: sex, power, and beheadings.',
  'the-venture-bros': 'Failure runs in the family. So does adventure.',
  'the-vietnam-war': 'The most comprehensive account of America\'s longest war.',
  'the-wonder-years': 'Growing up in the late 1960s. Forever remembered.',
  'the-world-at-war': 'The definitive documentary on World War II.',
  'tiger-king': 'Truth is stranger than fiction. Much, much stranger.',
  'timeless': 'A terrorist hijacks a time machine. Three heroes follow.',
  'tokyo-ghoul': 'He\'s half human, half ghoul, and struggling with both.',
  'tokyo-vice': 'An American journalist infiltrates the Tokyo underworld.',
  'torchwood': 'Outside the government, beyond the police.',
  'touch': 'An autistic boy sees patterns that connect everything.',
  'top-boy': 'The drug trade owns everything on these streets.',
  'top-of-the-lake': 'A detective investigates a girl\'s disappearance in New Zealand.',
  'trailer-park-boys': 'A Canadian mockumentary about very ambitious criminals.',
  'travelers': 'Consciousness from the future inhabits present-day bodies.',
  'twisted-metal': 'In a post-apocalyptic wasteland, a delivery driver fights to survive.',
  // ── U ──
  'ugly-betty': 'Brains, heart, and zero fashion sense. She\'s unstoppable.',
  'unbreakable-kimmy-schmidt': 'Rescued from a cult. Determined to live.',
  'upload': 'You can upload your consciousness to the afterlife. There\'s a catch.',
  'utopia': 'A comic book hides a deadly prophecy.',
  // ── V ──
  'v': 'They said they came in peace. They were lying.',
  'velma': 'The untold origin of mystery\'s most underappreciated mind.',
  'veronica-mars': 'She was prom queen. Now she\'s a private detective.',
  'vice-principals': 'Two vice principals, one job, no limits.',
  'victoria': 'A young queen finds her throne, her voice, and her love.',
  'vigil': 'A detective must investigate a death on a nuclear submarine.',
  'vikings-valhalla': 'The last great age of the Vikings begins.',
  'virgin-river': 'A nurse practitioner finds more than solitude in a small town.',
  // ── W ──
  'warehouse-13': 'Storing the world\'s most dangerous artifacts since 1898.',
  'warrior': 'A martial arts prodigy arrives in 1870s San Francisco Chinatown.',
  'warrior-nun': 'Resurrected by a holy artifact, she fights demons.',
  'wayward-pines': 'Nobody leaves Wayward Pines. Nobody.',
  'we-own-this-city': 'Baltimore\'s most corrupt police unit, and its unraveling.',
  'the-west-wing': 'A day in the life of an idealistic White House.',
  'wild-wild-country': 'A spiritual commune brought an Oregon town to its knees.',
  'wilfred': 'He\'s a man in a dog suit. Only Elijah Wood can see that.',
  'will-grace': 'A gay man and a straight woman, inseparable in New York.',
  'willow': 'The sorcerer returns to battle a new darkness.',
  'winning-time-the-rise-of-the-lakers-dynasty': 'Before the dynasty, there was the chaos.',
  'wizards-of-waverly-place': 'One teen will inherit the family magic. Which one?',
  'workaholics': 'Three college dropouts work at a telemarketing firm.',
  // ── X Y Z ──
  'x-men': 'Mutants fighting for a world that fears and hates them.',
  'x-men-97': 'The X-Men are back. The world is still afraid.',
  'xena-warrior-princess': 'She was a warlord. Now she seeks redemption.',
  'years-and-years': 'One British family lives through the next fifteen years.',
  'you-re-the-worst': 'Two terrible people fall accidentally in love.',
  'young-justice': 'The next generation of the Justice League.',
  'young-rock': 'The true story of how Dwayne Johnson became The Rock.',
  'your-friends-neighbors': 'When friendship and money mix, someone pays.',
  'your-honor': 'A judge\'s son causes a fatal accident. The cover-up begins.',
  'z-nation': 'The zombie apocalypse needs saviors. These aren\'t them.',
  'zero-day': 'A cyberattack destroys America. A former president investigates.',
  // Existing shows that need taglines added
  'a-discovery-of-witches': 'A witch discovers a bewitched manuscript. Everything follows.',
  'a-knight-of-the-seven-kingdoms': 'A hedge knight and his squire wander Westeros.',
  'a-man-on-the-inside': 'A retiree goes undercover in a retirement home.',
  'a-murder-at-the-end-of-the-world': 'A tech billionaire\'s retreat becomes a crime scene.',
  'according-to-jim': 'A dad with strong opinions and a patient family.',
  'agatha-all-along': 'The road is dangerous. So is Agatha.',
  'american-dad': 'Family values at their most satirical.',
  'anatomy-of-a-scandal': 'In Westminster, the powerful protect themselves.',
  'archive-81': 'Restoring old tapes uncovers something horrifying.',
  'ash-vs-evil-dead': 'Hail to the king, baby.',
  'atypical': 'Sam Gardner is on the spectrum and on the search for love.',
  'designated-survivor': 'The most unlikely man becomes the most powerful.',
  'dc-s-legends-of-tomorrow': 'Time-traveling misfits try not to break history.',
  'lost-in-space': 'A family of colonists crash on an alien world.',
  'making-a-murderer': 'The evidence said guilty. The truth was more complicated.',
  'married-with-children': 'The world\'s most dysfunctional family.',
  'my-name-is-earl': 'Karma exists. Earl is finding that out the hard way.',
  'oz': 'Maximum security. Minimum mercy.',
  'the-idol': 'A pop star trades one obsession for another.',
  'the-pitt': 'A Pittsburgh ER on the worst day of the year.',
  'titans': 'The Teen Titans have grown up. They\'re darker now.',
  'sirens': 'A perfect family reunion. Until it isn\'t.',
  'black-rabbit': 'One deal with the mob changes everything.',
  'frieren-beyond-journey-s-end': 'The elven mage lives on after the hero\'s victory.',
  'star-wars-visions': 'Star Wars as seen through the lens of anime.',
  'dark-winds': 'Two Navajo Tribal Police solve crimes in the 1970s Southwest.',
  'the-patient': 'A therapist is taken hostage by a serial killer in therapy.',
  'the-studio': 'Welcome to the most chaotic studio in Hollywood.',
  'smiling-friends': 'A company that makes people happy, somehow.',
  'blood-of-zeus': 'A bastard son of Zeus must save Mount Olympus.',
  'primal': 'A caveman and a T-Rex navigate a violent prehistoric world.',
  'hazbin-hotel': 'A hotel for rehabilitating demons. In Hell.',
  'scavengers-reign': 'Stranded on an alien planet of breathtaking danger.',
  'murderers-by-family': 'A family of killers in the American countryside.',
  'the-residence': 'An eccentric detective solves a murder at the White House.',
  'murder-she-wrote': 'Everywhere she goes, someone ends up dead.',
  'inside-job': 'Working for a secret shadow government is a nightmare.',
  'cosmos': 'Billions and billions of ways to see the universe.',
  'our-planet': 'The natural world needs us more than ever.',
  'blue-planet-ii': 'The ocean\'s greatest secrets, finally revealed.',
  'frozen-planet': 'The last great wilderness on Earth.',
  'human-planet': 'Humans survive everywhere. Even the impossible places.',
  'formula-1-drive-to-survive': 'The fastest sport. The fiercest personalities.',
  'the-vietnam-war': 'An epic history of America\'s most divisive war.',
  'the-world-at-war': 'The definitive account of the Second World War.',
  'wild-wild-country': 'A guru. A commune. An American town under siege.',
  'making-a-murderer': 'Two men. Questionable justice. Undeniable doubt.',
  'the-jinx-the-life-and-deaths-of-robert-durst': 'A documentary that led to a confession.',
  'american-vandal': 'The most important true crime investigation nobody took seriously.',
  'tiger-king': 'Joe Exotic: big cats, big crimes, big chaos.',
  'nathan-for-you': 'Business consulting at its most spectacularly useless.',
  'the-rehearsal': 'He rehearsed every scenario. Life still surprised him.',
  'jackass': 'Pain is funnier when it\'s someone else.',
  'mythbusters': 'Is it true? Let\'s explode something and find out.',
  // ── Additional TAG entries missing from initial pass ──
  '1923': 'A new chapter in the Dutton family saga.',
  '12-monkeys': 'Time travel. Plague. The fight to save humanity.',
  '24-live-another-day': 'The clock never stops. Neither does Jack Bauer.',
  '3rd-rock-from-the-sun': 'Aliens studying the human condition. From the inside.',
  '90210': 'New school. New drama. Same zip code.',
  '9-1-1': 'Every second counts.',
  'alien-earth': 'They\'re not alone on Earth.',
  'almost-human': 'In the future, every cop has a partner.',
  'an-idiot-abroad': 'One man. The whole world. No interest in either.',
  'berserk': 'In a world of darkness, one warrior fights on.',
  'blackadder': 'Medieval England\'s most cunning nobleman.',
  'blackadder-goes-forth': 'Cunning plans from the trenches of World War I.',
  'blackadder-ii': 'Blackadder in Elizabethan England.',
  'blackadder-the-third': 'Blackadder serves Prince George in Regency England.',
  'c-b-strike': 'A crippled private eye cracks London\'s darkest cases.',
  'castlevania': 'The night is filled with monsters.',
  'clarkson-s-farm': 'When a TV presenter tries farming. What could go wrong?',
  'coupling': 'Love, lust, and miscommunication.',
  'death-in-paradise': 'Murder in paradise. Every time.',
  'dopesick': 'One pill changed everything.',
  'dragon-ball': 'The adventure begins. Collect all seven Dragon Balls.',
  'dragon-ball-super': 'Even stronger. Even more epic.',
  'episodes': 'Hollywood ruins everything. Even friendships.',
  'evil': 'Is evil human? Or something more?',
  'extras': 'Being an extra: not as glamorous as you\'d hope.',
  'family-matters': 'Did I do that?',
  'frasier': 'Tossed salads and scrambled eggs.',
  'full-house': 'A family that never runs out of heart.',
  'gangs-of-london': 'London\'s criminal empires clash for control.',
  'griselda': 'The godmother of cocaine.',
  'happy': 'A hit man. An imaginary friend. A rescue mission.',
  'happy-endings': 'Six friends. No happy endings.',
  'heroes-reborn': 'The heroes return. So does the threat.',
  'hollywood': 'The golden age of Hollywood. Rewritten.',
  'how-i-met-your-father': 'How did she end up here?',
  'humans': 'What makes us human? Consciousness. Feeling. Choice.',
  'i-am-groot': 'He\'s Groot. That\'s enough.',
  'impractical-jokers': 'Four best friends dare each other to do the unthinkable.',
  'inhumans': 'The royal family of Attilan stands divided.',
  'john-adams': 'A new nation. An extraordinary man.',
  'jury-duty-presents-company-retreat': 'The verdict: more chaos.',
  'keeping-up-with-the-kardashians': 'Keeping up has never been so hard.',
  'lessons-in-chemistry': 'Chemistry is everywhere—even in the kitchen.',
  'letterkenny': 'Small town. Big mouths.',
  'm-a-s-h': 'War is hell. They made it funny.',
  'man-vs-bee': 'Man. Bee. No contest.',
  'master-of-none': 'Life, love, and pasta in New York.',
  'messiah': 'Is he a prophet? Or a terrorist?',
  'mom': 'Recovery is a family affair.',
  'monty-python-s-flying-circus': 'And now for something completely different.',
  'mr-inbetween': 'He takes care of problems. For a fee.',
  'mr-mrs-smith': 'Marriage is a spy game.',
  'one-day': 'Same day. Different years. One love story.',
  'over-the-garden-wall': 'Two brothers lost in a strange world.',
  'paradise': 'Paradise has a price.',
  'parasyte-the-maxim': 'Half human. Half alien. All heart.',
  'peep-show': 'Two flatmates. Two very different worldviews. One disaster.',
  'percy-jackson-and-the-olympians': 'The gods are real. And they\'re a problem.',
  'pok-mon': 'Gotta catch \'em all.',
  'poldark': 'A soldier returns home to fight for what\'s his.',
  'preacher': 'God is gone. Hell is empty. The hunt begins.',
  'resident-evil': 'The virus was just the beginning.',
  's-w-a-t': 'Protect and serve. At any cost.',
  'safe': 'Nothing is as safe as it seems.',
  'servant': 'Something is very wrong in this house.',
  'stargate-atlantis': 'A new stargate awaits in the Pegasus Galaxy.',
  'stargate-universe': 'Stranded billions of light years from home.',
  'steins-gate': 'The microwave turns messages into time travel.',
  'swamp-thing': 'He\'s not what he used to be.',
  'sword-art-online': 'In this game, dying means death.',
  'tales-from-the-crypt': 'The Crypt Keeper has a story for you.',
  'ted': 'America\'s favorite foul-mouthed teddy bear is back.',
  'teenage-mutant-ninja-turtles': 'Heroes in a half shell.',
  'terminator-the-sarah-connor-chronicles': 'The war for the future begins now.',
  'the-alienist': 'A killer stalks New York\'s darkest streets.',
  'the-blue-planet': 'The ocean covers most of our planet. We barely know it.',
  'the-chosen': 'Encounter the man who changed the world.',
  'the-daily-show': 'The most trusted name in fake news.',
  'the-filthy-frank-show': 'Totally offensive. Totally insane. Totally online.',
  'the-goldbergs': 'Growing up 80s. One awkward moment at a time.',
  'the-inbetweeners': 'Growing up is a nightmare.',
  'the-king-of-queens': 'The king of his castle. Sort of.',
  'the-kominsky-method': 'Getting older is no laughing matter. Except it is.',
  'the-perfect-couple': 'Perfect family. Imperfect secrets.',
  'the-promised-neverland': 'The children know the truth. Now they must escape.',
  'the-ranch': 'Coming home is never easy.',
  'the-serpent': 'A con man. A killer. A mystery spanning continents.',
  'the-stranger': 'One stranger. Every secret.',
  'the-walking-dead-daryl-dixon': 'Daryl Dixon takes his crossbow to France.',
  'the-walking-dead-dead-city': 'Maggie and Negan navigate a walker-infested Manhattan.',
  'the-walking-dead-the-ones-who-live': 'Rick and Michonne are finally reunited.',
  'the-white-queen': 'The war of the roses. Fought by queens.',
  'the-woman-in-the-house-across-the-street-from-the-girl-in-the-window': 'She saw something. Or did she?',
  'the-young-pope': 'A young, unpredictable pope shakes the Vatican.',
  'them': 'Something lurks in the neighborhood.',
  'time': 'In prison, time is your enemy.',
  'unforgotten': 'Cold cases. Warm hearts. Hard truths.',
  'victorious': 'Fame is the goal. Friends are the bonus.',
  'war-peace': 'Russia\'s greatest novel. Brought to life.',
  'why-women-kill': 'Three women. Three eras. One deadly instinct.',
  'whose-line-is-it-anyway': 'Where everything\'s made up and the points don\'t matter.',
  'younger': 'Forty is the new twenty-six.',
  'scenes-from-a-marriage': 'Love, resentment, and everything in between.',
};

// ── Apply data ─────────────────────────────────────────────────────────────────
const pool = JSON.parse(readFileSync(OUT_PATH, 'utf-8'));
let leadFilled = 0, tagFilled = 0, leadMissed = 0, tagMissed = 0;

for (const show of pool) {
  if (!show.topEpisodeLead && LEAD[show.id]) {
    show.topEpisodeLead = LEAD[show.id];
    leadFilled++;
  }
  if (!show.tagline && TAG[show.id]) {
    show.tagline = TAG[show.id];
    tagFilled++;
  }
  if (!show.topEpisodeLead) leadMissed++;
  if (!show.tagline) tagMissed++;
}

writeFileSync(OUT_PATH, JSON.stringify(pool, null, 2));
console.log(`Filled ${leadFilled} lead actors, ${tagFilled} taglines`);
console.log(`Still missing: ${leadMissed} leads, ${tagMissed} taglines`);
if (leadMissed > 0 || tagMissed > 0) {
  console.log('\nShows still missing data:');
  pool.filter(s => !s.topEpisodeLead || !s.tagline).forEach(s => {
    const miss = [!s.topEpisodeLead && 'LEAD', !s.tagline && 'TAG'].filter(Boolean).join('+');
    console.log(` [${miss}] "${s.id}" ${s.title}`);
  });
}
