/**
 * patchMissing.mjs
 * Direct patch for shows that still have null lead actors after addLeadActors.mjs
 */
import { readFileSync, writeFileSync } from 'fs';

const OUT_PATH = 'C:/Users/atoml/Documents/heatmap-guessr/data/puzzle_pool.json';

// Additional lead actors and taglines not caught by the main scripts
const EXTRA_LEADS = {
  'baby-reindeer':                         'Richard Gadd',
  'the-last-kingdom':                      'Alexander Dreymon',
  '3-body-problem':                        'Eiza González',
  'what-if':                               'Jeffrey Wright',
  'american-dad':                          'Seth MacFarlane',
  'the-acolyte':                           'Amandla Stenberg',
  'sharp-objects':                         'Amy Adams',
  'unbelievable':                          'Kaitlyn Dever',
  'dexter-resurrection':                   'Michael C. Hall',
  'foundation':                            'Jared Harris',
  'the-rookie':                            'Nathan Fillion',
  'the-man-in-the-high-castle':            'Alexa Davalos',
  '11-22-63':                              'James Franco',
  'psych':                                 'James Roday Rodriguez',
  'titans':                                'Brenton Thwaites',
  'maid':                                  'Margaret Qualley',
  'chilling-adventures-of-sabrina':        'Kiernan Shipka',
  'married-with-children':                 'Ed O\'Neill',
  'my-hero-academia':                      'Daiki Yamashita',
  'oz':                                    'Ernie Hudson',
  'the-idol':                              'Lily-Rose Depp',
  'my-name-is-earl':                       'Jason Lee',
  'russian-doll':                          'Natasha Lyonne',
  'tulsa-king':                            'Sylvester Stallone',
  'shrinking':                             'Jason Segel',
  'designated-survivor':                   'Kiefer Sutherland',
  'normal-people':                         'Daisy Edgar-Jones',
  'the-day-of-the-jackal':                 'Eddie Redmayne',
  'love-death-robots':                     'Various Artists',
  'the-good-fight':                        'Christine Baranski',
  'power':                                 'Omari Hardwick',
  'the-originals':                         'Joseph Morgan',
  'the-haunting-of-bly-manor':             'Victoria Pedretti',
  'the-act':                               'Joey King',
  'the-watcher':                           'Naomi Watts',
  'the-morning-show':                      'Jennifer Aniston',
  'the-pitt':                              'Noah Wyle',
  'the-heroes':                            'Various',
  'panchayat':                             'Jitendra Kumar',
  'the-last-dance':                        'Michael Jordan',
  'cosmos-a-spacetime-odyssey':            'Neil deGrasse Tyson',
  'planet-earth':                          'David Attenborough',
  'planet-earth-ii':                       'David Attenborough',
  'top-gear':                              'Jeremy Clarkson',
  'dc-s-legends-of-tomorrow':             'Caity Lotz',
  'a-knight-of-the-seven-kingdoms':        'Peter Claffey',
  'gen-v':                                 'Jaz Sinclair',
  'the-book-of-boba-fett':                 'Temuera Morrison',
  'she-hulk-attorney-at-law':              'Tatiana Maslany',
  'ms-marvel':                             'Iman Vellani',
  'peacemaker':                            'John Cena',
  'ahsoka':                                'Rosario Dawson',
  'star-wars-the-clone-wars':              'Matt Lanter',
  'star-trek-the-next-generation':         'Patrick Stewart',
  'star-trek-discovery':                   'Sonequa Martin-Green',
  'adventure-time':                        'Jeremy Shada',
  'batman-the-animated-series':            'Kevin Conroy',
  'spongebob-squarepants':                 'Tom Kenny',
  'gravity-falls':                         'Jason Ritter',
  'the-expanse':                           'Steven Strait',
  'battlestar-galactica':                  'Edward James Olmos',
  'firefly':                               'Nathan Fillion',
  'buffy-the-vampire-slayer':              'Sarah Michelle Gellar',
  'angel':                                 'David Boreanaz',
  'the-acolyte':                           'Amandla Stenberg',
  'deadwood':                              'Timothy Olyphant',
  'six-feet-under':                        'Peter Krause',
  'the-oa':                                'Brit Marling',
  'the-sinner':                            'Jessica Biel',
  'broadchurch':                           'Olivia Colman',
  'banshee':                               'Antony Starr',
  'penny-dreadful':                        'Eva Green',
  'black-sails':                           'Toby Stephens',
  'sense8':                                'Doona Bae',
  'entourage':                             'Adrian Grenier',
  '3-body-problem':                        'Eiza González',
  'alice-in-borderland':                   'Kento Yamazaki',
  'lupin':                                 'Omar Sy',
  '1899':                                  'Emily Beecham',
  'freaks-and-geeks':                      'Linda Cardellini',
  'schitt-s-creek':                        'Eugene Levy',
  'nine-perfect-strangers':               'Nicole Kidman',
  'the-haunting-of-hill-house':            'Michiel Huisman',
  'midnight-mass':                         'Hamish Linklater',
  'the-fall-of-the-house-of-usher':        'Bruce Greenwood',
  'weeds':                                 'Mary-Louise Parker',
  'curb-your-enthusiasm':                  'Larry David',
  'under-the-dome':                        'Mike Vogel',
  '2-broke-girls':                         'Kat Dennings',
  'atypical':                              'Keir Gilchrist',
  'lost-in-space':                         'Maxwell Jenkins',
  'misfits':                               'Robert Sheehan',
  'fawlty-towers':                         'John Cleese',
  'see':                                   'Jason Momoa',
  'halo':                                  'Pablo Schreiber',
  'dead-to-me':                            'Christina Applegate',
  'the-orville':                           'Seth MacFarlane',
  'stargate-sg-1':                         'Richard Dean Anderson',
  'the-twilight-zone':                     'Jordan Peele',
  'making-a-murderer':                     'Steven Avery',
  'under-the-dome':                        'Mike Vogel',
  'the-family-man':                        'Manoj Bajpayee',
  'halo':                                  'Pablo Schreiber',
  'dead-to-me':                            'Christina Applegate',
  'the-orville':                           'Seth MacFarlane',
  'fear-the-walking-dead':                 'Kim Dickens',
  'the-good-doctor':                       'Freddie Highmore',
  'the-mentalist':                         'Simon Baker',
  'designated-survivor':                   'Kiefer Sutherland',
  'titans':                                'Brenton Thwaites',
  'the-punisher':                          'Jon Bernthal',
  'the-100':                               'Eliza Taylor',
  'bosch':                                 'Titus Welliver',
  'bosch-legacy':                          'Titus Welliver',
  'the-blacklist':                         'James Spader',
  'billions':                              'Damian Lewis',
  'person-of-interest':                    'Jim Caviezel',
  'the-americans':                         'Keri Russell',
  'house-of-cards':                        'Kevin Spacey',
  'the-good-fight':                        'Christine Baranski',
  'power':                                 'Omari Hardwick',
  'suits':                                 'Gabriel Macht',
  'modern-family':                         'Ed O\'Neill',
  'the-expanse':                           'Steven Strait',
  'the-100':                               'Eliza Taylor',
  'dark':                                  'Louis Hofmann',
  'ozark':                                 'Jason Bateman',
  'succession':                            'Jeremy Strong',
  'the-sopranos':                          'James Gandolfini',
  'the-wire':                              'Dominic West',
  'game-of-thrones':                       'Peter Dinklage',
  'breaking-bad':                          'Bryan Cranston',
  'house-of-the-dragon':                   'Matt Smith',
  'succession':                            'Jeremy Strong',
  'the-bear':                              'Jeremy Allen White',
  'house':                                 'Hugh Laurie',
  'the-shield':                            'Michael Chiklis',
  'dexter':                                'Michael C. Hall',
  'the-sopranos':                          'James Gandolfini',
  'the-x-files':                           'David Duchovny',
  '24':                                    'Kiefer Sutherland',
  'the-mentalist':                         'Simon Baker',
  'sons-of-anarchy':                       'Charlie Hunnam',
  'the-walking-dead':                      'Andrew Lincoln',
  'criminal-minds':                        'Matthew Gray Gubler',
  'ncis':                                  'Mark Harmon',
  'monk':                                  'Tony Shalhoub',
  'white-collar':                          'Matt Bomer',
  'the-flash':                             'Grant Gustin',
  'arrow':                                 'Stephen Amell',
};

const EXTRA_TAGLINES = {
  'baby-reindeer':                         'It started with a free pint.',
  'the-last-kingdom':                      'Destiny is all.',
  '3-body-problem':                        'The universe is not what it seems.',
  'foundation':                            'The future of civilization rests on one man\'s vision.',
  'the-rookie':                            'He\'s not your average cop. He\'s a rookie.',
  'the-man-in-the-high-castle':            'What if the Allies had lost?',
  '11-22-63':                              'One man. One chance. Change history.',
  'psych':                                 'He sees things other people miss.',
  'maid':                                  'Sometimes you have to get low to rise up.',
  'chilling-adventures-of-sabrina':        'The darkness has a name.',
  'my-hero-academia':                      'Rise up. Be the hero.',
  'russian-doll':                          'She keeps dying. And coming back.',
  'tulsa-king':                            'A new city. Same old mob.',
  'shrinking':                             'Grief never looked so alive.',
  'normal-people':                         'Love, in all its complexity.',
  'the-day-of-the-jackal':                 'The world\'s most lethal assassin.',
  'power':                                 'Money. Drugs. Murder. Family.',
  'the-haunting-of-bly-manor':             'Some loves outlast a lifetime.',
  'the-act':                               'The truth is stranger than fiction.',
  'the-watcher':                           'Home is where the horror is.',
  'panchayat':                             'A city boy. A village story.',
  'the-expanse':                           'Some things are worth dying for.',
  'battlestar-galactica':                  'So say we all.',
  'firefly':                               'You can\'t take the sky from me.',
  'buffy-the-vampire-slayer':              'In every generation, one is chosen.',
  'angel':                                 'The vampire with a soul.',
  'six-feet-under':                        'Life is a work in progress.',
  'deadwood':                              'Gold. Power. Corruption.',
  'the-oa':                                'Every story has a beginning.',
  'entourage':                             'Hollywood\'s most promising actor. And his crew.',
  'banshee':                               'Fake it till you make it.',
  'penny-dreadful':                        'Where the darkest nightmare meets the deepest desire.',
  'black-sails':                           'The origins of the most feared pirate in history.',
  'sense8':                                'Eight minds. One soul.',
  'alice-in-borderland':                   'Play or die.',
  'lupin':                                 'The master of disguise.',
  '1899':                                  'Everything is connected.',
  'freaks-and-geeks':                      'A different kind of high school.',
  'schitt-s-creek':                        'Riches to rags. Family first.',
  'nine-perfect-strangers':               'A retreat from reality.',
  'the-haunting-of-hill-house':            'Some houses are alive.',
  'midnight-mass':                         'Faith can move mountains.',
  'weeds':                                 'One plant. One problem.',
  'curb-your-enthusiasm':                  'No hugging. No learning. Zero manners.',
  'under-the-dome':                        'What\'s inside is trying to get out.',
  '2-broke-girls':                         'Two girls. Zero money. Infinite dreams.',
  'see':                                   'In a world without sight, one sense rules all.',
  'halo':                                  'The universe will never be the same.',
  'dead-to-me':                            'Grief is complicated. So is friendship.',
  'the-orville':                           'A crew. A ship. A mission impossible.',
  'fawlty-towers':                         'Check in to the worst hotel in Britain.',
  'misfits':                               'Community service was never this dangerous.',
  'the-family-man':                        'A spy. A father. A double life.',
  'stargate-sg-1':                         'The greatest adventure in the universe.',
  'the-twilight-zone':                     'You\'re traveling through another dimension.',
  'fear-the-walking-dead':                 'Dead don\'t discriminate.',
  'bosch':                                 'Hard-boiled. Hard-nosed. Hard to stop.',
  'bosch-legacy':                          'The legend continues.',
  'power':                                 'Money. Drugs. Murder. Family.',
  'billions':                              'Power. Money. Corruption.',
  'suits':                                 'Success isn\'t everything. Winning is.',
  'the-good-fight':                        'The fight isn\'t over.',
  'dark':                                  'The beginning is the end.',
};

const pool = JSON.parse(readFileSync(OUT_PATH, 'utf-8'));

let enrichedLead = 0, enrichedTagline = 0;
for (const show of pool) {
  if (!show.topEpisodeLead && EXTRA_LEADS[show.id]) {
    show.topEpisodeLead = EXTRA_LEADS[show.id];
    enrichedLead++;
  }
  if (!show.tagline && EXTRA_TAGLINES[show.id]) {
    show.tagline = EXTRA_TAGLINES[show.id];
    enrichedTagline++;
  }
}

writeFileSync(OUT_PATH, JSON.stringify(pool, null, 2), 'utf-8');
console.log(`Patched ${enrichedLead} lead actors, ${enrichedTagline} taglines.`);
console.log(`Shows with lead actor: ${pool.filter(s => s.topEpisodeLead).length}`);
console.log(`Shows with tagline: ${pool.filter(s => s.tagline).length}`);
console.log(`Still missing lead: ${pool.filter(s => !s.topEpisodeLead).length}`);
console.log(`Still missing tagline: ${pool.filter(s => !s.tagline).length}`);
